export const USER_SPACE_BASH_COMMANDS = [
  "echo",
  "cat",
  "printf",
  "ls",
  "mkdir",
  "rmdir",
  "touch",
  "rm",
  "cp",
  "mv",
  "ln",
  "chmod",
  "pwd",
  "readlink",
  "head",
  "tail",
  "wc",
  "stat",
  "grep",
  "fgrep",
  "egrep",
  "sed",
  "awk",
  "sort",
  "uniq",
  "comm",
  "cut",
  "paste",
  "tr",
  "rev",
  "nl",
  "fold",
  "expand",
  "unexpand",
  "strings",
  "split",
  "column",
  "join",
  "tee",
  "find",
  "basename",
  "dirname",
  "tree",
  "du",
  "env",
  "printenv",
  "alias",
  "unalias",
  "history",
  "true",
  "false",
  "clear",
  "bash",
  "sh",
  "jq",
  "base64",
  "diff",
  "date",
  "sleep",
  "timeout",
  "time",
  "seq",
  "expr",
  "md5sum",
  "sha1sum",
  "sha256sum",
  "file",
  "html-to-markdown",
  "help",
  "which",
  "tac",
  "hostname",
  "whoami",
  "od",
  "gzip",
  "gunzip",
  "zcat",
] as const;

export const USER_SPACE_BASH_CUSTOM_COMMANDS = ["glob", "checkout", "checkin", "ruok"] as const;
export const USER_SPACE_BASH_MOUNT_NAME = "office";
export const USER_SPACE_BASH_PUBLIC_COMMANDS = [
  ...USER_SPACE_BASH_COMMANDS,
  ...USER_SPACE_BASH_CUSTOM_COMMANDS,
] as const;

export const USER_SPACE_BASH_EXECUTION_LIMITS = {
  maxCommandCount: 500,
  maxLoopIterations: 1000,
  maxCallDepth: 20,
  maxStringLength: 2 * 1024 * 1024,
} as const;

export const USER_SPACE_BASH_BOUNDARY_SUMMARY = [
  "This is a browser-side just-bash shell over the active User Space, not a host/container shell.",
  "Only registered commands and shell builtins are available; there is no external executable lookup.",
  "No network, sockets, package managers, VCS, compilers, databases, Python, JavaScript runtimes, or host process control.",
  "Recursive content search uses the file-tree index through grep -r/-R; recursive path matching uses the indexed glob command, while find/tree provide metadata traversal.",
  "checkout accepts rootName/path file references and returns a session-relative Agent Space shared/path; that path is not visible inside this shell. checkin accepts an Agent Space path plus an optional rootName/path destination, otherwise it creates a result in User Space shared/.",
  "Text files should normally stay remote and use read/write/edit; checkout/checkin are intended mainly for binary files.",
  "sed -i, awk system(), and find -exec/-execdir/-delete/-ok/-okdir are unavailable.",
  "cp and mv operate on files only; shell-created symlinks last only for the current shell invocation.",
  "The shell has only the virtual root / and the active browser-authorized directory under /<current user space name>; mounted names update with the active User Space and host paths do not exist.",
] as const;

export function formatUserSpaceBashCapabilities(): string {
  return [
    "User Space bash capability boundary",
    "",
    ...USER_SPACE_BASH_BOUNDARY_SUMMARY.map((line) => `- ${line}`),
    "- Supported shell syntax: pipelines, redirections, heredocs/here strings, &&/||, variables/export, command substitution, globs, and subshells.",
    `- Execution limits: ${USER_SPACE_BASH_EXECUTION_LIMITS.maxCommandCount} commands, ${USER_SPACE_BASH_EXECUTION_LIMITS.maxLoopIterations} loop iterations, call depth ${USER_SPACE_BASH_EXECUTION_LIMITS.maxCallDepth}, string size ${USER_SPACE_BASH_EXECUTION_LIMITS.maxStringLength} bytes.`,
    "",
    `Registered commands (${USER_SPACE_BASH_PUBLIC_COMMANDS.length}):`,
    USER_SPACE_BASH_PUBLIC_COMMANDS.join(" "),
    "",
    "Prefer the dedicated top-level user-space read, write, and edit tools for text; use this shell for bounded pipelines, indexed search, and binary transfer.",
  ].join("\n");
}
