/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.test.jsonc --include-runtime=false --strict-vars=false --env-interface=TestEnv src/test-configuration.d.ts` (hash: 414e29e12d3f36fb67b7b1991170ac38)
interface __BaseEnv_TestEnv {
	PIWORK_WRAPPER_CONFIG: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./test-index");
	}
	interface Env extends __BaseEnv_TestEnv {}
}
interface TestEnv extends __BaseEnv_TestEnv {}
