/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.example.jsonc --include-runtime=false --strict-vars=false --env-interface=WrapperExampleEnv src/wrapper-configuration.d.ts` (hash: 2e96d1d5ecb74605401b3217c85d3e17)
interface __BaseEnv_WrapperExampleEnv {
	PIWORK_WRAPPER_CONFIG: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./example-wrapper");
	}
	interface Env extends __BaseEnv_WrapperExampleEnv {}
}
interface WrapperExampleEnv extends __BaseEnv_WrapperExampleEnv {}
