import type { DeepPartialUiCopy, UiCopy } from "./types.js";

export const enUSCopyOverrides = {
  browserBridge: {
    title: "Chrome browser bridge",
    trigger: "Chrome browser bridge",
    connected: "Connected",
    waiting: "Waiting for extension",
    stopped: "Service stopped",
    starting: "Starting",
    unavailable: "Runtime unavailable",
    failed: "Connection error",
    description: "Let the Agent operate authorized Chrome pages through structured CDP actions.",
    connectedDescription:
      "The Chrome extension is connected. The Agent can use semantic snapshots to operate pages.",
    waitingDescription:
      "The bridge is running. Load the Chrome extension, then verify the connection.",
    stoppedDescription: "Start the local bridge, then load the extension in Chrome.",
    unavailableDescription: "Build the pinned agent-browser runtime before connecting Chrome.",
    errorDescription: "The bridge is temporarily unavailable. Refresh or start it again.",
    runtime: "Runtime",
    daemon: "Bridge service",
    extension: "Chrome extension",
    ready: "Ready",
    online: "Online",
    offline: "Offline",
    version: "Version",
    source: "Source revision",
    port: "Port",
    tabs: (count: number) => `${count} tabs`,
    sessions: (count: number) => `${count} Agent sessions`,
    connectedProfiles: (count: number) => `${count} Chrome profiles connected`,
    setupTitle: "First-time setup",
    stepOne: "Open chrome://extensions and turn on Developer mode.",
    stepTwo: "Choose Load unpacked, then select the directory below.",
    stepThree: "Keep the target page open, then return here to verify the connection.",
    extensionPath: "Extension directory",
    copyPath: "Copy extension directory",
    pathCopied: "Extension directory copied",
    start: "Start bridge",
    startingAction: "Starting...",
    verify: "Verify connection",
    verifying: "Verifying...",
    verifySuccess: (durationMs: number) => `Connection verified (${durationMs} ms)`,
    refresh: "Refresh status",
    close: "Close",
    missingArtifacts: (items: string) => `Missing: ${items}`,
    controlTitle: "Current session control",
    agentControl: "Agent is controlling",
    takeoverPending: "Handing control to you",
    humanControl: "You are controlling",
    resumingControl: "Returning control to the Agent",
    stoppingControl: "Stopping browser control",
    stoppedControl: "Browser control stopped",
    uncertainControl: "Control state needs confirmation",
    controlEpoch: (epoch: number) => `Control epoch ${epoch}`,
    takeOver: "Take over browser",
    takingOver: "Taking over...",
    resumeControl: "Return to Agent",
    resumingControlAction: "Returning...",
    stopControl: "Stop browser control",
    stoppingControlAction: "Stopping...",
    handoffLabel: "Tell the Agent what you changed",
    handoffPlaceholder: "For example: I signed in and selected the target account.",
    handoffDescription:
      "After control is returned, the Agent will read the page again before continuing.",
    pendingActionRisk:
      "The interrupt was not confirmed. Check the page before allowing another submit or click.",
    privacyNotice:
      "The Agent may read the authorized page structure, text, and necessary screenshots. Status does not expose page URLs or content.",
    selectSession: "Select a session to manage browser control.",
  },
  common: {
    archive: "Archive",
    archiveChat: "Archive chat",
    attachImage: "Attach image",
    attachImages: "Attach images",
    backend: "Backend",
    cancel: "Cancel",
    close: "Close",
    conversation: "Conversation",
    create: "Create",
    delete: "Delete",
    deleting: "Deleting",
    dismiss: "Dismiss",
    edit: "Edit",
    chatActions: "Chat actions",
    hide: "Hide",
    listSeparator: ", ",
    loading: "Loading...",
    messageInput: "Message input",
    model: "Model",
    paste: "Paste",
    pasteClipboard: "Paste from clipboard",
    preview: "Preview",
    processing: "Processing...",
    removeImage: "Remove image",
    reload: "Reload",
    retry: "Retry",
    rename: "Rename",
    restore: "Restore",
    save: "Save",
    saving: "Saving",
    search: "Search",
    selectModel: "Select model",
    sendMessage: "Send message",
    showDetails: "Show details",
    skipToMainContent: "Skip to main content",
    text: "Text",
    stopGeneration: "Stop generation",
    switchModel: "Switch model",
    taskDescription: "Task description",
    user: "User",
    currentModel: (model: string) => `Current model: ${model}`,
    removeNamedItem: (name: string) => `Remove ${name}`,
  },
  app: {
    checkingAuth: "Checking sign-in status...",
    description: "All-in-One Paperwork Agent Workspace",
    documentTitle: "All-in-One Paperwork Agent Workspace",
    enteringWorkbench: "Entering the agent workbench...",
    enterWorkbenchFailed: "Failed to enter workbench",
    restoringWorkbench: "Restoring the agent workbench...",
    syncingAccountSession: "Syncing account session...",
  },
  apps: {
    title: "Apps",
    description:
      "Publish Agent results to your Cloudflare account or create a one-time Temporary Account preview.",
    backToWorkbench: "Back to workbench",
    filterLabel: "App list scope",
    filters: {
      currentSession: "Current session",
      mine: "Mine",
      tenant: "Tenant",
    },
    refresh: "Refresh Apps",
    loading: "Loading Apps...",
    loadFailed: "Failed to load Apps",
    retry: "Reload",
    empty: {
      currentSessionTitle: "This session has no Apps yet",
      currentSessionDescription:
        "Ask the Agent to build an App in Agent Space, then choose Temporary or BYOC deployment here.",
      mineTitle: "You have no Apps yet",
      mineDescription: "Apps built from any of your Agent sessions will appear here.",
      tenantTitle: "This tenant has no Apps",
      tenantDescription: "Apps built and linked by tenant members will appear here.",
    },
    noCurrentSession: "There is no current session to filter by.",
    loadMore: "Load more",
    screenshotAlt: (name: string) => `Application screenshot for ${name}`,
    screenshotPending: "A screenshot will appear when the preview is ready",
    owner: "Owner",
    updatedAt: (date: string) => `Updated ${date}`,
    sourceSession: "Source session",
    stableUrl: "Stable URL",
    urlNotReady: "The Cloudflare URL is not ready yet",
    version: (number: number) => `Version ${number}`,
    status: {
      building: "Building",
      needs_action: "Needs action",
      deploying: "Deploying",
      preview: "Temporary preview",
      ready: "Ready",
      failed: "Failed",
      archived: "Archived",
    },
    phase: {
      building: "Building",
      awaiting_target: "Waiting for deployment target",
      awaiting_oauth: "Waiting for Cloudflare OAuth",
      queued: "Queued",
      provisioning: "Preparing Cloudflare resources",
      deploying: "Deploying",
      temporary_ready: "Temporary preview ready",
      claim_pending: "Waiting for Temporary Account claim",
      verifying_claim: "Verifying claimed account",
      ready: "Deployment ready",
      expired: "Temporary preview expired",
      failed: "Deployment failed",
      cancelled: "Deployment cancelled",
    },
    targetKind: {
      unassigned: "Not selected",
      temporary: "Temporary Account",
      byoc: "Cloudflare BYOC",
    },
    open: "Open App",
    copyUrl: "Copy URL",
    urlCopied: "App URL copied",
    preview: "Preview App",
    manage: "Manage App",
    detailsTitle: (name: string) => `Manage ${name}`,
    detailsDescription:
      "Choose a Cloudflare deployment target, review deployment phases, and manage Temporary claims or OAuth BYOC.",
    closeDetails: "Close App management panel",
    overview: "Overview",
    deploymentTarget: "Deployment target",
    currentDeployment: "Current deployment",
    deploymentHistory: "Deployment history",
    deploymentsEmpty: "No deployments yet",
    currentVersion: "Current version",
    rollback: "Roll back to this version",
    rollingBack: "Rolling back...",
    rollbackSucceeded: "Rollback deployment created; choose its Cloudflare target",
    deploymentEvents: "Deployment events",
    deploymentEventsEmpty: "No deployment lifecycle events yet",
    chooseTarget: "Choose a Cloudflare deployment target",
    chooseTargetDescription:
      "Temporary is for a one-time preview. Use a Cloudflare account connected through OAuth for permanent deployment.",
    deploymentTargetsLoading: "Loading available Cloudflare deployment targets...",
    deploymentTargetsConfigUnavailable:
      "Piwork could not confirm which Cloudflare deployment targets this server enables, so submission is blocked. Return to development and try again.",
    deploymentTargetsUnavailable:
      "This server does not enable Temporary Account or OAuth BYOC deployment. Return to development, try again later, or contact your administrator.",
    deploymentTargetsUnavailableAction: "Return to development",
    temporaryTarget: "Temporary preview",
    byocTarget: "OAuth BYOC",
    temporaryDescription:
      "Temporary Accounts support only a stateless Worker and Static Assets, normally expire in about 60 minutes, and are limited to one preview per unconnected user.",
    byocDescription:
      "Piwork uses only the selected OAuth-authorized account and deploys an ordinary Cloudflare Worker from the App manifest.",
    acceptCloudflareTerms: "Confirm acceptance of the Cloudflare Terms of Service",
    acceptCloudflarePrivacy: "Confirm acceptance of the Cloudflare Privacy Policy",
    acceptTermsPrefix: "I have read and agree to the",
    acceptPrivacyPrefix: "I have read and agree to the",
    cloudflareTerms: "Cloudflare Terms of Service",
    cloudflarePrivacy: "Cloudflare Privacy Policy",
    cloudflareAccount: "Cloudflare account",
    selectCloudflareAccount: "Select a connected account",
    cloudflareAccountOption: (name: string, id: string) => `${name} (${id})`,
    noCloudflareConnection: "No active Cloudflare OAuth connection is available.",
    additionalOAuthPermissionsRequired: (permissions: string[]) =>
      `The selected connection lacks required App permissions (${permissions.join(", ")}). Reconnect Cloudflare to grant them.`,
    connectCloudflare: "Connect Cloudflare account",
    connectingCloudflare: "Opening Cloudflare...",
    deployToTarget: "Deploy to this target",
    selectingTarget: "Submitting deployment...",
    targetSelected: "Deployment target submitted",
    turnstile: {
      label: "Cloudflare Turnstile verification",
      loadingConfig: "Loading Temporary Account security configuration...",
      configUnavailable:
        "Turnstile configuration is unavailable, so a Temporary preview cannot be created.",
      loading: "Loading Cloudflare Turnstile verification...",
      verified: "Cloudflare Turnstile verification complete.",
      failed: "Cloudflare Turnstile verification failed or expired. Verify again.",
      retry: "Verify again",
    },
    deploymentFailed: "Cloudflare deployment failed",
    oauthConnected: "Cloudflare account connected. Reopen the App details to select it.",
    oauthCancelled:
      "Cloudflare OAuth was cancelled. No account was connected and no deployment was resumed.",
    oauthAccountMismatch:
      "The OAuth account does not match the claimed Temporary Account. Piwork did not claim or resume the deployment. Select the account that claimed this preview, or redeploy to another account.",
    chooseClaimedAccount: "Choose claimed account again",
    redeployToAnotherAccount: "Redeploy to another account",
    retryOAuth: "Reconnect Cloudflare",
    temporaryExpired:
      "The Temporary preview or claim link expired. Create a new Temporary preview or switch to OAuth BYOC.",
    createNewTemporaryPreview: "Create a new Temporary preview",
    retryDeployment: "Return to development and redeploy",
    previewExpiresIn: (remaining: string) => `Preview time remaining: ${remaining}`,
    claimExpiresIn: (remaining: string) => `Claim link time remaining: ${remaining}`,
    countdown: {
      unavailable: "Unavailable",
      expired: "Expired",
      hoursMinutes: (hours: number, minutes: number) => `${hours} hr ${minutes} min`,
      minutesSeconds: (minutes: number, seconds: number) => `${minutes} min ${seconds} sec`,
    },
    claimTemporaryPreview: "Claim this preview in Cloudflare",
    claimThenConnectCloudflare: "Connect Cloudflare after claiming",
    claimRequiresByoc:
      "The Temporary preview remains available. Claiming it for continued Piwork management requires Cloudflare BYOC.",
    claimOwnerOnly: "Only the owner who created this Temporary preview can open its claim link.",
    claimThenOAuth:
      "After claiming, authorize the same Cloudflare account through OAuth before Piwork can continue deployment.",
    workerDomain: {
      title: "Worker Custom Domain",
      description:
        "Attach an exact hostname from the same Cloudflare account to a ready BYOC Worker. This uses ordinary Workers Custom Domains only.",
      defaultUrlRetained:
        "The default workers.dev URL is permanently retained. Attaching or detaching a domain never removes it.",
      connection: "Cloudflare connection",
      selectConnection: "Select the connection that deployed this Worker",
      zone: "Cloudflare zone",
      loadingZones: "Loading available zones...",
      selectZone: "Select an active zone",
      noActiveZones:
        "This connection has no available active zone, or OAuth does not grant zone access.",
      hostname: "Exact hostname",
      hostnameDescription:
        "Enter a complete hostname in the selected zone. Wildcards are not supported.",
      hostnamePlaceholder: "app.example.com",
      wildcardNotAllowed: "Worker Custom Domains do not allow wildcard hostnames.",
      invalidHostname: "Enter an exact hostname that belongs to the selected active zone.",
      status: {
        pending: "Attaching",
        active: "Active",
        failed: "Attach failed",
        removing: "Detaching",
      },
      sslStatus: {
        pending_validation: "Certificate awaiting validation",
        pending_issuance: "Certificate issuing",
        active: "Certificate active",
        failed: "Certificate failed",
      },
      detachCertificateImpact:
        "Detaching removes only the hostname route from the Worker. It does not delete the Advanced Certificate automatically issued by Cloudflare.",
      confirmImpact: "Confirm Worker Custom Domain impact",
      confirmAttachImpact:
        "I confirm this exact hostname will route to the Worker and understand that existing DNS or routing may be affected.",
      confirmDetachImpact:
        "I confirm detaching will stop the hostname's Worker route. The workers.dev URL and automatically issued Advanced Certificate remain.",
      attach: "Attach Worker Custom Domain",
      attaching: "Attaching...",
      attached: "Worker Custom Domain attach submitted",
      detach: "Detach Worker Custom Domain",
      detaching: "Detaching...",
      detached: "Worker Custom Domain detach submitted",
    },
    continueDevelopment: "Continue development",
    continuingDevelopment: "Opening the development session...",
    archive: "Archive and unlink",
    archiving: "Archiving...",
    archiveConfirm: (name: string) =>
      `Archive “${name}” and unlink it from Piwork? This will not delete or disable your Cloudflare Worker, domains, or other resources.`,
    archived: "App archived; Cloudflare resources are unchanged",
    archivedAt: (date: string) => `Archived ${date}; Cloudflare resources were not deleted`,
    archivedResourcesRemain:
      "Archiving only unlinks Piwork. It does not delete Cloudflare resources.",
    unarchive: "Unarchive",
    unarchiving: "Unarchiving...",
    unarchived: "App unarchived",
    previewTitle: (name: string) => `${name} App preview`,
    previewDescription:
      "The preview runs directly on the user's Cloudflare origin and does not receive the Piwork sign-in cookie.",
    closePreview: "Close App preview",
    previewUnsafe: "This preview URL is not a supported independent HTTPS Cloudflare origin.",
    previewLoading: "Loading App preview...",
    actionFailed: "App operation failed",
  },
  piRuntime: {
    connectionTimeout: "Timed out waiting for the Pi session connection.",
    invalidSessionCreateResponse: "The session service returned invalid Pi runtime data.",
    noModels:
      "No model is available for this Agent. Check the model policy, credentials, and network policy.",
    sessionCreationFailed: "Pi session creation failed.",
    sessionCreateStreamEnded: "The Pi session creation stream ended before returning a result.",
    thinkingLevel: "Reasoning effort",
    thinkingLevels: {
      off: "Off",
      minimal: "Minimal",
      low: "Low",
      medium: "Medium",
      high: "High",
      xhigh: "Extra high",
      max: "Maximum",
    },
    reasoningModelDescription: "Pi model with reasoning levels",
    standardModelDescription: "Pi model",
    toolStatus: {
      started: "Started",
      running: "Running",
      completed: "Completed",
      failed: "Failed",
      cancelled: "Cancelled",
    },
  },
  interaction: {
    askTitle: "Your answer is needed",
    planTitle: "Confirm execution plan",
    submit: "Submit answer",
    freeTextLabel: "Free-text answer",
    freeTextPlaceholder: "Enter your answer…",
    freeTextOption: "Enter a free-text answer",
    finishSelection: "Finish selection",
    executePlan: "Execute plan",
    continuePlanning: "Continue planning",
    refinePlan: "Refine plan",
    submitRefinement: "Submit refinement",
    refinementLabel: "Plan refinement",
    refinementPlaceholder: "Describe what should be changed or expanded…",
    sessionClosed: "The session connection is closed. Reconnect and try again.",
    timedOut: "Interaction timed out",
  },
  chat: {
    activeGroup: "Active",
    archivedSessions: "Archived sessions",
    archiveSession: (title: string) => `Archive ${title}`,
    archived: {
      bulkDelete: "Delete",
      bulkDeleteFailed: "Failed to delete selected sessions",
      bulkDeleteConfirm: (count: number) =>
        `Delete ${count} archived sessions? This will delete the session directories and history and cannot be undone.`,
      bulkRestore: "Restore",
      bulkRestoreFailed: "Failed to restore archived sessions",
      createdAt: (date: string) => `Created ${date}`,
      delete: "Delete",
      deleteFailed: "Failed to delete",
      deleteOneConfirm: (title: string) =>
        `Delete "${title}"? This will delete the session directory and history and cannot be undone.`,
      empty: "No archived sessions",
      loading: "Loading archived sessions...",
      loadFailed: "Failed to load archived sessions",
      restore: "Restore",
      restoreFailed: "Failed to restore archived session",
      selectAll: "Select all archived sessions",
      selectedCount: (count: number) => `Selected ${count}`,
      selectSession: "Select session",
      selectSessionLabel: (title: string) => `Select archived session ${title}`,
      title: "Archived sessions",
      unknownAgent: "Default Agent",
      archivedAt: (date: string) => `Archived ${date}`,
    },
    assistantAndSessionSelector: "Digital agent and session selector",
    backendTheme: {
      system: { label: "System", description: "Follow system appearance" },
      light: { label: "Light", description: "Use light theme" },
      dark: { label: "Dark", description: "Use dark theme" },
    },
    createSession: "Create session",
    selectSession: "Select session",
    createAgentSession: (name: string) => `Create ${name} session`,
    deleteArchivedManyConfirm: (count: number) =>
      `Delete ${count} archived sessions? This will delete the session directories and history and cannot be undone.`,
    deleteArchivedOneConfirm: (title: string) =>
      `Delete "${title}"? This will delete the session directory and history and cannot be undone.`,
    agentSelector: "Select agent",
    errors: {
      preferencesLoadFailed: "Failed to load preferences",
      preferencesSaveFailed: "Failed to save preferences",
      renameFailed: "Rename failed",
      startAgentFailed: "Failed to start agent",
    },
    emptyState: {
      title: "What can I do for you?",
      description:
        "Mount a local folder to collaborate on files, or describe the task you want your agent to move forward.",
      mountUserSpace: "Open user space",
      summarizeDirectory: "Review and summarize this folder",
      createPlan: "Create an implementation plan",
      blankTask: "Start with a blank task",
    },
    idleGroup: "Idle",
    loadMoreSessions: "Load more sessions",
    noSessionMessages: "No messages",
    noMessages: "No messages",
    noSessions: "No sessions",
    now: "Just now",
    preferencesPanel: {
      accountInfo: "Account information",
      appearance: "Appearance and language",
      close: "Close",
      closeLabel: "Close personal settings",
      fileDefaultOpenMode: "Default file opening mode",
      labels: {
        displayName: "Username",
        email: "Email",
        org: "Organization",
        roles: "Roles",
        username: "Username",
      },
      title: "Personal settings",
      office: {
        title: "Default Office file opening mode",
        preview: "Preview",
        edit: "Edit",
      },
      officeResources: {
        title: "Office resources",
        description:
          "Required resources are prepared as documents open; common fonts can be installed ahead of time.",
        version: (version: string) => `OnlyOffice ${version}`,
        checking: "Checking",
        updating: "Updating",
        ready: "Ready",
        incomplete: "Not fully downloaded",
        updateAvailable: "Update available",
        paused: "Paused",
        repairNeeded: "Repair needed",
        error: "Operation failed",
        statusUnavailable: "Resource status is temporarily unavailable",
        summary: (completed: number, total: number) => `${completed} / ${total} files cached`,
        failedFiles: (count: number) => `${count} files failed to load`,
        progressLabel: "Office resource cache progress",
        downloadProgress: (completed: string, total: string) =>
          `Downloading ${completed} / ${total}`,
        verifyProgress: (completed: string, total: string) => `Verifying ${completed} / ${total}`,
        phases: {
          idle: "Idle",
          planning: "Planning",
          downloading: "Downloading",
          verifying: "Verifying",
          activating: "Finishing update",
          repairing: "Repairing",
          paused: "Paused",
        },
        categoryProgressLabel: (category: string) => `${category} cache progress`,
        categories: {
          fonts: "Fonts",
          core: "Common runtime and x2t",
          word: "Word",
          cell: "Spreadsheet",
          slide: "Presentation",
        },
        fontsTitle: "Font packages",
        basicPreset: "Prepare essentials",
        compatibilityPreset: "Install Office-compatible fonts",
        advanced: "Advanced resources and fonts",
        packReady: "Installed",
        packOnDemand: "On demand",
        storageNote: "Resources stay in this browser and do not use Piwork workspace storage.",
        required: "Required",
        download: "Download",
        remove: "Remove",
        downloadAll: "Download all",
        checkAndRepair: "Check and repair",
        pause: "Pause",
        resume: "Resume",
        retry: "Retry",
        reopenHint: "Font changes take effect after reopening the Office document.",
        failedResource: (path: string) => `Affected resource: ${path}`,
        errors: {
          statusUnavailable: "Office resource status is unavailable. Check the network and retry.",
          offline: "You are offline. The download can resume when the connection returns.",
          network: "A resource download failed. Try again.",
          timeout: "A resource download timed out. Resume or retry.",
          integrity: "A resource failed integrity verification. Repair the affected resource.",
          quota: "There is not enough browser storage. Free space and try again.",
          manifest: "The Office resource manifest is invalid.",
          incompatible:
            "This Office resource release is incompatible with the current Piwork build.",
          storage: "The Office resource installation state could not be saved.",
          aborted: "The Office resource operation was cancelled.",
          insufficientStorage: (available: string, required: string) =>
            `Not enough browser storage: ${available} available, ${required} required. Free space or leave private browsing.`,
        },
      },
      filePanel: {
        title: "File panel",
      },
      nativeHelper: {
        title: "Native helper",
        description:
          "Connect Piwork Helper to use macOS preview, open, print, export, share, and native editing for files.",
        checking: "Checking",
        unsupported: "Not supported on this system",
        notInstalled: "Not installed",
        offline: "Installed, but offline",
        incompatible: "Version incompatible",
        connected: "Connected",
        updateAvailable: "Update available",
        version: (version: string) => `Current version ${version}`,
        latestVersion: (version: string) => `Latest version ${version}`,
        capabilities: (count: number) => `${count} native capabilities available`,
        refresh: "Refresh status",
        copyInstallCommand: "Copy install command",
        copyUpgradeCommand: "Copy upgrade command",
        copied: "Command copied",
        lastError: (message: string) => `Last error: ${message}`,
      },
      userSpace: {
        showHiddenEntries: "Show hidden files",
        showHiddenEntriesDescription:
          "Show dot-prefixed paths in the user-space file tree and tree.",
        title: "User space",
      },
    },
    preferences: "Personal settings",
    reloadSessions: "Reload sessions",
    runningGroup: "Running",
    searchSession: "Search sessions",
    sessionName: "Session name",
    sessionGroupLabel: (label: string) => `${label} sessions`,
    sessionSelector: "Select session",
    renameSession: (title: string) => `Rename ${title}`,
    renameSessionEmpty: "Enter a session name",
    startingAgentSession: (name: string) => `Starting ${name} agent...`,
    agentSessionStarted: "Digital agent session started",
    sessionTime: {
      minutesAgo: (value: number) => `${value} minutes ago`,
      hoursAgo: (value: number) => `${value} hours ago`,
      daysAgo: (value: number) => `${value} days ago`,
    },
    userDetails: "User details",
    userMenu: {
      admin: "Admin console",
      destroyAndLogout: "Destroy workbench and log out",
      keyboardShortcuts: "Keyboard shortcuts",
      logout: "Log out",
      theme: "Appearance",
      themeOption: (label: string) => `Appearance: ${label}`,
    },
    keyboardShortcuts: {
      title: "Keyboard shortcuts",
      close: "Close keyboard shortcuts",
      sections: {
        workspace: "Workspace",
        chat: "Chat",
      },
      actions: {
        sessionSearch: "Search sessions",
        fileSearch: "Search files",
        toggleFilePreview: "Expand or collapse file preview",
        toggleSessionPanel: "Expand or collapse the session area",
        toggleSpacePanel: "Expand or collapse the User | Agent space panel",
        newLine: "New line",
        sendMessage: "Send message",
        togglePlanMode: "Toggle plan mode",
        openShortcutReference: "Open keyboard shortcuts",
      },
      conditions: {
        filePreviewOpen: "Available only when the file preview panel is open",
      },
      keys: {
        command: "⌘",
        b: "B",
        control: "Ctrl",
        shift: "Shift",
        enter: "Enter",
        f: "F",
        k: "K",
        p: "P",
        slash: "/",
        tab: "Tab",
        u: "U",
      },
    },
    waitingReply: "Waiting for reply",
  },
  composer: {
    connectionUnavailable:
      "The workbench connection is offline. You can send again after it reconnects.",
    defaultFileRefMessage: "Please review the user-space file I referenced.",
    defaultImageMessage: "Please review the attached image.",
    dropImages: "Drop images here",
    planLabel: "Plan",
    previewReferencedFile: (name: string) => `Preview referenced file ${name}`,
    shortcuts: "Enter for a new line · Shift+Enter to send · Shift+Tab for plan mode",
  },
  appError: {
    recoverPageDescription: "Reload the page to recover. The error has been reported.",
    runtimeErrorTitle: "A runtime error occurred",
    sectionLoadFailed: (label?: string) =>
      label ? `${label} failed to load` : "Section failed to load",
  },
  agentGovernance: {
    approvedSkills: "Approved Skills",
    controlPlane: "Agent control plane",
    defaultDescription:
      "Configure knowledge, Skills, MCP, and network boundaries, then publish an immutable version.",
    draftOnly: "Draft only",
    empty:
      "This tenant has no available Agents yet. A non-deletable general Agent is created automatically after personal-tenant migration.",
    governance: "Agent governance",
    instructions: "Runtime instructions",
    instructionsHint: "Saving does not affect published versions",
    instructionsPlaceholder:
      "Describe this Agent's responsibilities, working style, and boundaries...",
    knowledgeDirectories: "Read-only knowledge directories",
    mcpConnections: "MCP connections",
    networkPolicies: "Network policies",
    policyHint:
      "Resource references must belong to the current tenant. Unscanned or unapproved Skills, revoked MCP connections, cross-tenant directories, and invalid network policies are rejected at publish time.",
    publish: "Publish version",
    published: "Published",
    publishedMessage: (version: number) =>
      `Version v${version} published; new sessions will be pinned to it.`,
    refresh: "Refresh Agents",
    saveDraft: "Save draft",
    savedMessage: "Draft saved. Running sessions are unaffected.",
    selectAgent: "Select a Agent to view governance settings",
  },
  diff: {
    noChanges: "No changes",
  },
  login: {
    authFailed: "Authentication failed",
    brand: "Piwork Workbench",
    confirmPassword: "Confirm password",
    connectAuthService: "Connecting to authentication service...",
    createAccount: "Create account",
    disabledRegistration: "Self-registration is currently disabled",
    email: "Email",
    login: "Log in",
    loginServiceUnavailable:
      "Login service is temporarily unavailable. Contact your system administrator.",
    missingSignInFields: "Enter an email and password",
    missingSignUpFields: "Enter your name, email, and password confirmation",
    missingEnterpriseName: "Enter an enterprise or organization name.",
    missingTeamName: "Enter a team name.",
    name: "Name",
    password: "Password",
    passwordMismatch: "The two passwords do not match",
    registrationClosed: "Registration closed",
    registration: {
      enterprise: {
        description: "A usage profile for organization governance and delegated administration",
        title: "Enterprise",
      },
      personal: {
        description: "A usage profile for individual tasks and private local folders",
        title: "Personal",
      },
      team: {
        description: "A usage profile for small-team collaboration and shared workflows",
        title: "Team",
      },
    },
    privacyNote:
      "Your account isolates local workbench data. Model credentials are securely injected per session by the platform.",
    signInDescription: "Sign in to continue your local agent sessions.",
    signUpDescription:
      "Choose the collaboration model that fits now. Advanced Agents, knowledge bases, and permissions can be configured later; registration takes about a minute.",
    signUpTitle: "Create your workspace",
    signUp: "Sign up",
    switchToLogin: "Switch to login",
    switchToSignUp: "Switch to sign up",
    title: "Agent Workbench",
    usageMode: "How you'll use it",
    teamName: "Team name",
    teamNamePlaceholder: "For example: Product engineering",
    organizationName: "Enterprise or organization name",
    organizationNamePlaceholder: "For example: Acme Corporation",
  },
  folderPicker: {
    clearFilter: "Clear filter",
    close: "close",
    closeButton: "Close",
    directoryBreadcrumb: "Directory breadcrumb",
    dialogLabel: "Select folder",
    filterDirectories: "Filter directories",
    filterPlaceholder: "Filter...",
    loadDirectoryFailed: "Could not load directory",
    loadingDirectories: "Loading directories",
    manualPath: "Type path manually",
    navigate: "navigate",
    navigateInto: (name: string) => `Navigate into ${name}`,
    noMatchingDirectories: "No matching directories",
    noSubdirectories: "No subdirectories",
    parent: "parent",
    recent: "Recent",
    recentDirectories: "Recent directories",
    retry: "Retry",
    select: "select",
    selectButton: "Select",
    selectDirectory: (name: string) => `Select ${name}`,
    subdirectories: "Subdirectories",
    title: "Select Folder",
    typeDirectoryPath: "Type a directory path",
  },
  message: {
    collapseThinking: "Collapse thinking",
    expandThinking: "Expand thinking",
    imageAttachmentAlt: "attachment",
    noThinking: "No thinking content yet.",
    previewReferencedFile: (name: string) => `Preview referenced file ${name}`,
    showAll: "Show all",
    showTail: "Show tail",
    thinkingDone: "Thought",
    thinkingStreaming: "Thinking",
    tailStatus: (shown: number, total: number) => `last ${shown} of ${total}`,
    totalLines: (count: number) => `${count} line${count === 1 ? "" : "s"}`,
  },
  messageFeed: {
    assistantStreaming: "Assistant response streaming",
    contextOrganizing: "Organizing context...",
    loadMore: (count: number) => `Load ${count} more`,
    hiddenCount: (count: number) => `(${count} hidden)`,
    loadOlder: "Load older session history",
    loadingOlder: "Loading older history...",
    reloadSessionHistory: "Reload session history",
    sessionHistoryLoadFailedRetry: "Session history failed to load. Click to retry.",
    scrollToBottom: "Scroll to bottom",
    workStepsRunning: (count: number) => `${count} work step${count > 1 ? "s" : ""} running`,
  },
  messageToc: {
    emptyMessage: "Empty message",
    imageMessage: "Image message",
    jumpToMessage: (ordinal: number, preview: string) => `Jump to message ${ordinal}: ${preview}`,
    label: "Message table of contents",
  },
  permission: {
    askUser: {
      customAnswer: "Other, enter your answer",
      fallbackQuestion: "Please confirm the next step.",
      interruptQuestion: "Ignore the question and interrupt the tool",
      multipleChoice: "Multiple choice",
      next: "Next",
      nextQuestion: "Next question",
      previous: "Previous",
      previousQuestion: "Previous question",
      singleChoice: "Single choice",
    },
    exitPlan: {
      adjustPlaceholder: "No, describe how to adjust it",
      continuePlanInstruction: "Please continue planning and adjust the approach",
      continuePlanningPlaceholder: "No, describe what to keep planning",
      exitAction: "Exit plan mode",
      exitTitle: "Exit plan mode?",
      implementAction: "Yes, implement this plan",
      implementTitle: "Implement this plan?",
    },
    approvalDetailFallback: "Needs your approval before continuing.",
    approve: "Approve",
    denyMessage: "Denied by user",
    hideDetails: "Hide details",
    interruptMessage: "Tool interrupted",
    planApprovalRequested: "Plan approval requested",
    reject: "Reject",
    requestedPermissions: "Requested permissions",
    reviewNeeded: "Review needed",
    showDetails: "Show details",
    suggestion: {
      addDirectories: (directory: string, scope: string) => `Trust ${directory} ${scope}`,
      addRules: (rule: string, scope: string) => `Approve "${rule}" ${scope}`,
      always: "always",
      fallback: (scope: string) => `Approve ${scope}`,
      forSession: "for this session",
      setMode: (mode: string) => `Approve and set mode to "${mode}"`,
      tool: (tool: string, scope: string) => `Approve ${tool} ${scope}`,
    },
    sessionClosed: "The session is closed. Re-enable it before answering.",
    submit: "Submit",
  },
  pwaPlatform: {
    eyebrow: "Desktop compatibility",
    titles: {
      mobile: "Mobile devices aren't supported",
      safari: "Safari isn't supported",
      firefox: "Firefox isn't supported",
      other: "This browser isn't supported",
      "desktop-chromium": "This browser isn't supported",
    },
    descriptions: {
      mobile:
        "Piwork is a desktop workbench designed for mouse, keyboard, and multi-window workflows. Phones and tablets aren't supported.",
      safari:
        "Piwork depends on desktop Chromium file-system and installation capabilities, so Safari isn't supported.",
      firefox:
        "Piwork depends on desktop Chromium file-system and installation capabilities, so Firefox isn't supported.",
      other: "This environment is not a supported desktop Chromium browser.",
      "desktop-chromium": "This environment is not a supported desktop Chromium browser.",
    },
    requirement:
      "Use the latest Chrome, Microsoft Edge, or another Chromium browser on a desktop computer.",
    matrixTitle: "Support scope",
    supported: "Supported",
    unsupported: "Not supported",
    desktopChromium: "Desktop Chrome / Edge / Chromium",
    safariFirefox: "Safari and Firefox",
    mobileDevices: "Phones and tablets",
    retry: "Check again",
    installTitle: "Keep Piwork on your desktop",
    installBody: "Install it to open the workbench in its own window from your system launcher.",
    install: "Install desktop app",
    installing: "Opening install prompt…",
    updateTitle: "A new version is ready",
    updateBody: "Save files you're editing before updating and reopening the workbench.",
    update: "Update after saving",
    updating: "Updating…",
    updateBlocked: "Unsaved files are still open. Save them before updating.",
    updateFailed: "The update could not finish. Reload and try again.",
    offlineTitle: "You're offline",
    offlineBody: "Sessions and files never use cached account data. Reconnect to continue.",
    pwaUnavailableTitle: "This address can't install the desktop app",
    pwaUnavailableBody:
      "The workbench still works. To install it, open Piwork over HTTPS, localhost, or 127.0.0.1.",
    swUnavailableBody:
      "Service Workers are disabled in this Chromium environment, so installation and the offline page are unavailable.",
    registrationErrorTitle: "Desktop app features didn't start",
    registrationErrorBody:
      "Service Worker registration failed. The workbench still works; reload to try again.",
    reload: "Reload",
    dismiss: "Dismiss",
  },
  rbacAdmin: {
    add: "Add",
    allMembersCount: (count: number) => `All members · ${count} total`,
    assignedCount: (count: number, noun: string) => `${count} ${noun}`,
    audit: {
      detail: "Record details",
      empty: "No audit records yet",
      matchedEmpty: "No matching audit records",
      recordCount: (filtered: number, total: number) => `${filtered} / ${total} records`,
      recordId: (id: string) => `Record ID: ${id}`,
      actorId: (id: string) => `Actor ID: ${id}`,
      resourceId: (type: string, id: string | null | undefined) => `Resource ID: ${type}:${id}`,
      searchLabel: "Search audit records",
      searchPlaceholder: "Search actors, resources, or actions",
      title: "Audit",
      unknownActor: "Unknown user",
      unknownTarget: "Target resource",
      actionSummary: {
        bootstrapAdmin: (target: string) => `Initialized ${target} as a system administrator`,
        denied: "Attempted to access an unauthorized admin feature",
        departmentCreate: (target: string) => `Created department ${target}`,
        departmentUpdate: (target: string) => `Edited department ${target}`,
        departmentDelete: (target: string) => `Deleted department ${target}`,
        departmentRolesReplace: (target: string) => `Changed roles for department ${target}`,
        roleCreate: (target: string) => `Created role ${target}`,
        roleUpdate: (target: string) => `Edited role ${target}`,
        roleDelete: (target: string) => `Deleted role ${target}`,
        rolePermissionsReplace: (target: string) => `Changed permissions for role ${target}`,
        userCreate: (target: string) => `Created user ${target}`,
        userRolesReplace: (target: string) => `Changed roles for member ${target}`,
        userDepartmentsReplace: (target: string) => `Changed departments for member ${target}`,
        userPasswordReset: (target: string) => `Reset password for member ${target}`,
        systemSettingsUpdate: "Changed system settings",
        fallback: (action: string) => `Performed ${action}`,
        withActor: (actor: string, action: string) => `${actor} ${action}`,
      },
    },
    cancel: "Cancel",
    close: "Close",
    closeDepartmentMenu: "Close department actions menu",
    create: "Create",
    dashboard: {
      back: "Back to workbench",
      loading: "Loading admin data...",
      noPermission: "No admin access",
      noPermissionDescription: "Contact an administrator to request access.",
      subtitle: "Members, departments, roles, and audit",
      title: "Access Management",
    },
    delete: "Delete",
    department: {
      addExistingUser: "Add existing user",
      addUser: {
        duplicate: "This user is already in this department",
        inputPlaceholder: "Enter a name or email",
        joined: "Member added to department",
        missing: "Enter the target user",
        notFound: "Target user not found. Select one from the suggestions.",
        searching: "Searching...",
        targetUser: "Target user",
        title: "Add user to department",
      },
      createChild: "Create child department",
      createSuccess: "Department created",
      delete: "Delete department",
      deleteDescription:
        "Enter the full department name before deleting. Departments with child departments or members cannot be deleted.",
      deleteSuccess: "Department deleted",
      edit: "Edit department",
      emptyName: "Department name cannot be empty",
      expand: "Expand department",
      collapse: "Collapse department",
      operation: (name: string) => `${name} actions`,
      name: "Department name",
      parent: "Parent department",
      parentLabel: (name: string) => `Parent department: ${name}`,
      root: "Root department",
      roles: "Department roles",
      searchMembers: "Search members",
      selectFirst: "Select a department first",
      selectPlaceholder: "Select a department",
      sortOrder: "Sort order",
      tableTitle: "Department tree",
      totalMembers: (count: number) => `${count} member${count === 1 ? "" : "s"} total`,
      typeConfirm: (name: string) => `Type "${name}" to confirm`,
      updateSuccess: "Department saved",
    },
    description: "Description",
    edit: "Edit",
    member: {
      department: "Department",
      directRoles: "Direct roles",
      edit: "Edit member",
      editUser: (name: string) => `Edit ${name}`,
      informationSaved: "Member information saved",
      loading: "Loading members...",
      matchedEmpty: "No matching members",
      name: "Member",
      permissions: "Permissions",
      roles: "Roles",
      unassigned: "Unassigned",
      operations: "Actions",
    },
    none: "None",
    noDescription: "No description",
    noOptions: "No options yet",
    pagination: {
      next: "Next page",
      previous: "Previous page",
    },
    password: {
      emptyNew: "New password cannot be empty",
      initial: "Initial password",
      emptyInitial: "Initial password cannot be empty",
      new: "New password",
      reset: "Reset password",
      resetConfirm: "Confirm reset",
      resetSuccess: "Password reset",
    },
    role: {
      create: "Create role",
      createSuccess: "Role created",
      delete: "Delete role",
      deleteSuccess: "Role deleted",
      edit: "Edit role",
      editRole: (name: string) => `Edit role ${name}`,
      emptyName: "Role name cannot be empty",
      name: "Role name",
      permissionCount: (count: number) => `${count} item${count === 1 ? "" : "s"}`,
      permissions: "Permissions",
      system: "System",
      systemReadonly: "System roles cannot be edited",
      title: "Role permissions",
      titleMeta: (roleCount: number, permissionCount: number) =>
        `${roleCount} roles, ${permissionCount} permissions`,
      updateSuccess: "Role saved",
    },
    save: "Save",
    searchNameOrEmail: "Search name or email",
    searchUsersLabel: "Search users",
    settings: {
      registrationDisabled: "Registration disabled",
      registrationEnabled: "Registration enabled",
      registrationLabel: "Allow self-registration",
      registrationDescription:
        "When disabled, the login page no longer shows the registration entry point.",
      subtitle: "Manage basic system switches",
      title: "System settings",
    },
    tabs: {
      audit: "Audit",
      agents: "Agent governance",
      label: "Access management sections",
      members: "Members and departments",
      roles: "Role permissions",
      settings: "System settings",
      users: "User management",
    },
    tagPicker: {
      add: "Add",
      duplicate: (label: string) => `${label} already exists`,
      inputPlaceholder: "Enter a department name",
      missing: (title: string) => `Enter ${title}`,
      notFound: (title: string) =>
        `${title.replace(/^所属/, "")} not found. Select one from the suggestions.`,
      remove: (id: string) => `Remove ${id}`,
    },
    user: {
      confirmPassword: "Confirm password",
      create: "Create user",
      createSuccess: "User created",
      createSubtitle: "Create a member account and assign departments and roles",
      displayName: "Name",
      emptyDisplayName: "Name cannot be empty",
      emptyEmail: "Email cannot be empty",
      email: "Email",
      passwordMismatch: "The two passwords do not match",
    },
  },
  markdownEditor: {
    blockEdit: {
      textGroup: {
        label: "Text",
        text: "Body",
        h1: "Heading 1",
        h2: "Heading 2",
        h3: "Heading 3",
        h4: "Heading 4",
        h5: "Heading 5",
        h6: "Heading 6",
        quote: "Quote",
        divider: "Divider",
      },
      listGroup: {
        label: "Lists",
        bulletList: "Bulleted list",
        orderedList: "Numbered list",
        taskList: "Task list",
      },
      advancedGroup: {
        label: "Insert",
        image: "Image",
        codeBlock: "Code block",
        table: "Table",
        math: "Math",
      },
    },
    codeMirror: {
      copy: "Copy",
      edit: "Edit",
      hide: "Hide",
      loading: "Loading...",
      noResult: "No results",
      preview: "Preview",
      searchLanguage: "Search language",
    },
    loadFailed: "Failed to load Markdown editor",
    imageBlock: {
      captionPlaceholder: "Add image caption",
      confirm: "Confirm",
      inlineUpload: "Upload",
      pasteLink: "or paste a link",
      uploadImage: "Upload image",
    },
    linkTooltip: {
      pasteLink: "Paste link...",
    },
    placeholder: "Type content, or press / to insert",
    topBar: {
      label: "Markdown editing toolbar",
      paragraph: "Body",
      stylePicker: "Block style",
      actions: {
        bold: "Bold",
        italic: "Italic",
        strikethrough: "Strikethrough",
        bulletList: "Bulleted list",
        orderedList: "Numbered list",
        taskList: "Task list",
        table: "Table",
        codeBlock: "Code block",
        quote: "Quote",
        divider: "Divider",
      },
    },
  },
  session: {
    defaultName: "New chat",
    launchFailed: "Launch failed",
    openWorkbench: "Opening workbench",
    prepareWorkbench: "Preparing workbench",
    startAgentFailed: "Failed to start agent",
  },
  timeline: {
    approved: "Approved",
    cancelled: "Cancelled",
    expandPlan: "Expand plan",
    expandPlanContent: "Expand plan content",
    noThinking: "No thinking content yet.",
    noToolDetails: "No tool details available.",
    plan: "Plan",
    subagent: "Subagent",
    stopTask: "Stop task",
    stoppingTask: "Stopping…",
    task: "Task",
    thinking: "Thinking",
    thinkingDone: "Thought",
    thinkingStreaming: "Thinking",
    rejected: "Rejected",
    collapsePlan: "Collapse plan",
    unansweredAnswers: ["Unanswered", "Awaiting answer"],
    waitingAnswer: "Awaiting answer",
  },
  topBar: {
    language: "Language",
    languageOption: (label: string) => `Language: ${label}`,
    languages: {
      zhCN: { label: "中文", description: "使用中文界面" },
      enUS: { label: "English", description: "Use English interface" },
    },
    openUserMenu: "Open user menu",
    toggleSidebar: "Toggle sidebar",
    userMenu: "User menu",
    workspace: "Workspace",
  },
  toolExecution: {
    active: "Active",
    workStepsRunning: (count: number) => `${count} work step${count > 1 ? "s" : ""} running`,
  },
  toolSummary: {
    awaitingApproval: (count: number) => `${count} awaiting approval`,
    running: (count: number) => `${count} running`,
    stepsCompleted: (count: number, seconds: string) =>
      `${count} work steps completed in ${seconds}s`,
    steps: (count: number) => `${count} step${count > 1 ? "s" : ""}`,
    errors: (count: number) => `${count} error${count > 1 ? "s" : ""}`,
  },
  toolBlock: {
    actionLabels: {
      bash: "Running command",
      read: "Reading file",
      write: "Writing file",
      edit: "Editing file",
      ask: "Waiting for answer",
      task: "Coordinating task",
      todo_write: "Updating todos",
      propose_plan: "Preparing plan confirmation",
      deploy_app: "Publishing App",
      open_app_preview: "Opening App preview",
      mcp_tool_call: "Using connection",
    },
    details: "Details",
    diff: "diff",
    editNumber: (index: number, total: number) => `Edit ${index}/${total}`,
    hide: "Hide",
    labels: {
      bash: "Command",
      read: "Read",
      write: "Write",
      edit: "Edit",
      ask: "Question",
      task: "Subagent",
      todo_write: "Todos",
      propose_plan: "Plan",
      deploy_app: "Publish App",
      open_app_preview: "App preview",
      mcp_tool_call: "Connection",
    },
    previewNeedsApproval: "needs approval",
    task: "Task",
    taskCount: (count: number) => `${count} task${count !== 1 ? "s" : ""}`,
    timeout: (value: string) => `timeout: ${value}ms`,
    working: "Working",
  },
  userSpace: {
    add: "Add user space",
    agentSpace: "Agent space",
    alreadyMounted: (name: string) => `User space "${name}" is already mounted.`,
    mountNameConflictDialog: {
      confirmTitle: "A folder with this name is already mounted",
      confirmDescription: (name: string) =>
        `A user space named “${name}” is already mounted. Give the selected folder a different alias?`,
      renameAction: "Set alias",
      renameTitle: "Set user space alias",
      renameDescription: (name: string) =>
        `“${name}” is already in use. Enter a new name for this user space.`,
      nameLabel: "User space alias",
      confirmRename: "Set alias and mount",
      enterName: "Enter a new user space name.",
    },
    accessToggleTitle: (access: "readonly" | "readwrite") =>
      access === "readonly" ? "Switch to read/write" : "Switch to read-only",
    audioPreviewTitle: (name: string) => `Audio preview ${name}`,
    clipboardAnnouncements: {
      agentCut: (count: number) => `Cut ${count} item${count === 1 ? "" : "s"} in Agent space.`,
      cancelled: "Cut cancelled.",
      userCut: (count: number) => `Cut ${count} item${count === 1 ? "" : "s"} in User space.`,
    },
    closeCurrentPreviewTab: "Close Current",
    closeOtherPreviewTabs: "Close Others",
    closeAllPreviewTabs: "Close All",
    pinPreviewTab: "Pin tab",
    unpinPreviewTab: "Unpin tab",
    unpinAllPreviewTabs: "Unpin all",
    closeAllPinnedPreviewTabs: "Close all pinned",
    closeOfficeSaveAlert: "Close Office save alert",
    closePreview: (title: string) => `Close preview ${title}`,
    collapseSpacePanel: "Collapse User | Agent space panel",
    collapsePinnedPreviewTabs: "Collapse pinned tabs",
    collapseSessionPanel: "Collapse session panel",
    expandSpacePanel: "Expand User | Agent space panel",
    expandPinnedPreviewTabs: "Expand pinned tabs",
    expandSessionPanel: "Expand session panel",
    textEditorLabel: (name: string) => `Text editor ${name}`,
    contextMenu: {
      addToConversation: "Add to conversation",
      copy: "Copy",
      cut: "Cut",
      createCopy: "Create copy",
      delete: "Delete",
      deleteFolder: "Delete folder",
      details: "Details",
      newFile: "New file",
      newFileTypes: {
        word: "Word document",
        ppt: "PowerPoint presentation",
        excel: "Excel spreadsheet",
        text: "Text file",
      },
      newFolder: "New folder",
      nativeQuickLook: "Quick Look",
      nativeOpen: "Open in Default App",
      nativeOpenWith: "Open With…",
      nativeEdit: "Edit in Native App",
      nativeEditing: "Editing natively",
      nativeActionFailed: (message: string) => `File action failed: ${message}`,
      nativeReclaim: "Reclaim to Piwork",
      nativeAbandon: "Abandon Native Edit",
      nativePrint: "Print…",
      nativeSaveAs: "Export Copy…",
      open: "Open",
      openAndPin: "Open and pin",
      openAsText: "Open as text",
      pasteHere: "Paste here",
      pasteToRoot: (name: string) => `Paste into the ${name} root folder`,
      preparingShare: "Preparing to share…",
      rename: "Rename",
      share: "Share…",
      shareFailed: (message: string) => `Sharing failed: ${message}`,
      shareUnavailable: "This file can’t be shared",
      transferToAgent: "Transfer to Agent space",
      transferToUser: "Transfer to User space",
    },
    nativeEdit: {
      handoffTitle: "Hand off to a native app?",
      handoffClean: (name: string) =>
        `“${name}” is open in Piwork. Its preview will close before the default native app opens it.`,
      handoffDirty: (name: string) =>
        `“${name}” has unsaved changes. Piwork will save and close it before opening the default native app. The native app will not open if saving fails.`,
      closeAndOpen: "Close and Open Natively",
      saveCloseAndOpen: "Save and Open Natively",
      conflictTitle: "The file changed in both places",
      conflictDescription:
        "The Piwork source also changed during native editing. Choose how to continue so nothing is silently overwritten.",
      saveAsCopy: "Save as Copy",
      overwrite: "Overwrite with Native Version",
      reclaimed: "The native version was reclaimed to Piwork.",
      noChanges: "The native file did not change. The editing handoff is complete.",
      abandoned: "Native editing was abandoned and the managed copy was removed.",
      savedCopy: (path: string) => `The native version was saved as “${path}”.`,
      errors: {
        fileReadFailed: "The file contents could not be read.",
        mountUnavailable: "User Space is offline, so the native edit cannot be reclaimed yet.",
        sourceChanged: "The source file changed before reclaim completed.",
      },
    },
    dragAndDrop: {
      agentInvalidDestination: "The selected items cannot be moved to that location.",
      agentInvalidSource: "The selected items no longer exist or cannot be moved.",
      agentMoveFailed: "The selected items could not be moved. The file tree was reloaded.",
      agentRollbackFailed:
        "The move could not be fully rolled back. The file tree was reloaded; check the current file locations.",
      agentTargetExists: "An item with the same name already exists at the destination.",
      copySuccess: (count: number, target: string) =>
        `Copied ${count} item${count === 1 ? "" : "s"} to ${target ? `“${target}”` : "the root folder"}.`,
      items: (count: number) => `${count} items`,
      moveSuccess: (count: number, target: string) =>
        `Moved ${count} item${count === 1 ? "" : "s"} to ${target ? `“${target}”` : "the root folder"}.`,
      processing: "Processing files…",
    },
    alerts: {
      mountSuccess: "User space mounted. Restore access next time.",
      transferAlreadyExistsTitle: "File already exists",
      transferSuccessTitle: "File transfer complete",
    },
    createDialog: {
      folderTitle: "New folder",
      fileTitle: "New file",
      locationRoot: "Create in user space root",
      locationPath: (path: string) => `Create in ${path}`,
      nameLabel: "Name",
      defaultFileName: "New file.txt",
      defaultFileNames: {
        word: "New word.docx",
        ppt: "New ppt.pptx",
        excel: "New excel.xlsx",
        text: "New text.txt",
      },
      processing: "Processing",
    },
    defaultFileName: "File",
    defaultRootName: "User space",
    deleteDialog: {
      folderTitle: "Delete folder?",
      fileTitle: "Delete file?",
      selectionTitle: "Delete selected items?",
      folderDescription: (path: string) => `This will delete ${path} and its contents.`,
      fileDescription: (path: string) => `This will delete ${path}.`,
      selectionDescription: (count: number) =>
        `This will delete ${count} selected items. Items already covered by selected folders will not be deleted twice.`,
    },
    detailsDialog: {
      title: "Details",
      selectionTitle: (count: number) => `${count} item details`,
      description: (space: string) => `From ${space}`,
      selectionDescription: (space: string) => `Selected items from ${space}`,
      labels: {
        fileCount: "Total files",
        name: "Name",
        modifiedAt: "Modified",
        path: "Path",
        size: "Size",
        totalSize: "Total size",
        type: "Type",
        typeCounts: "File types",
      },
      noFiles: "No files",
      typeCount: (type: string, count: number) => `${type} ${count}`,
      typeFile: "File",
      typeFolder: "Folder",
      fileTypes: {
        ai: "Adobe Illustrator document",
        bmp: "BMP image",
        csv: "Comma-separated values document",
        dmg: "Disk image",
        doc: "Word 97-2003 document",
        docx: "Office Open XML word processing document",
        gif: "GIF image",
        html: "HTML document",
        jpeg: "JPEG image",
        jpg: "JPEG image",
        json: "JSON document",
        log: "Log file",
        markdown: "Markdown document",
        md: "Markdown document",
        mov: "QuickTime movie",
        mp3: "MP3 audio",
        mp4: "MPEG-4 movie",
        pdf: "PDF document",
        png: "PNG image",
        ppt: "PowerPoint 97-2003 presentation",
        pptx: "Office Open XML presentation",
        psd: "Adobe Photoshop document",
        svg: "SVG document",
        txt: "Plain text document",
        wav: "Waveform audio",
        webp: "WebP image",
        xls: "Excel 97-2003 worksheet",
        xlsx: "Office Open XML spreadsheet",
        xml: "XML document",
        zip: "ZIP archive",
      },
      unknownSize: "Unknown",
    },
    searchDialog: {
      buttonTitle: "Search files",
      openFor: (name: string) => `Search ${name} user space`,
      modeLabel: "Search mode",
      pathMode: "Name",
      contentMode: "Content",
      inputLabel: "Search query",
      pathPlaceholder: "Search file names...",
      contentPlaceholder: "Search file contents...",
      noResults: "No matches",
      openResult: (path: string) => `Open search result ${path}`,
      fileResult: "File",
      folderResult: "Folder",
      lineResult: (line: number) => `Line ${line}`,
      matchCount: (count: number) => (count === 1 ? "1 hit" : `${count} hits`),
    },
    directoryEmpty: "Folder is empty",
    directoryLoadFailed: "Failed to read folder",
    directoryLoadMore: "Load more",
    directoryLoadTimeout: "Folder read timed out. Try again.",
    directoryLoading: "Loading folder",
    directoryRuntimeRestarting: "User space is recovering. Retrying automatically.",
    restoreAccess: "Restore access",
    restoreAccessFor: (name: string) => `Restore access to ${name}`,
    expand: "Expand",
    collapse: "Collapse",
    expandPreview: "Expand file preview",
    filePreview: "File preview",
    foldPreview: "Collapse file preview",
    popOutPreviewDropHint: "Release to detach the tab into a new window",
    openPreviewInNewWindow: "Open in new window",
    allowPreviewPopups: "Allow multiple separate windows",
    previewPopupsBlocked: (count: number) =>
      `Chrome blocked ${count === 1 ? "1 separate window" : `${count} separate windows`}. In the address bar pop-up notice, always allow this site, then retry.`,
    retryOpeningPreviewWindows: "Retry opening",
    returnPreviewToTabs: "Return to tab group",
    wterm: {
      title: "wterm",
      open: "Open wterm",
      requiresMountedWorkspace: "Mount a user space first",
    },
    htmlPreviewTitle: (name: string) => `HTML preview ${name}`,
    imagePreview: {
      saveFailed: "Failed to save image.",
      unsupportedFormat: "This image format cannot be edited yet",
      reset: "Reset image zoom",
      zoomIn: "Zoom in",
      zoomOut: "Zoom out",
      editor: {
        toolbar: "Image editing toolbar",
        select: "Select",
        crop: "Crop",
        pen: "Pen",
        arrow: "Arrow",
        rectangle: "Rectangle",
        ellipse: "Ellipse",
        text: "Text",
        undo: "Undo",
        redo: "Redo",
        color: "Color",
        customColor: "Custom color",
        strokeWidth: "Stroke width",
        applyCrop: "Apply crop",
        textPlaceholder: "Enter text",
        loading: "Loading image editor",
        loadFailed: "Failed to load image editor",
      },
    },
    mountMenuLabel: "User space folder",
    mountSwitcherDialog: {
      title: "Manage user space folders",
      currentAria: (name: string) => `${name}, current folder`,
      choose: (name: string) => `Switch to ${name}`,
      empty: "No folders are mounted yet.",
      aliasLabel: (name: string) => `Alias for ${name}`,
      renameAlias: (name: string) => `Rename ${name}`,
      finishRename: (name: string) => `Finish renaming ${name}`,
      addDirectory: "Add folder",
      save: "Save configuration",
      saving: "Saving…",
      saved: "User space configuration saved.",
    },
    mountRequiresSecureContext:
      "User space requires a secure context that supports File System Access (HTTPS or localhost)",
    noConnection: "Not connected",
    noSelection: "None selected",
    office: {
      cancelledSave: "Save cancelled",
      cancelledWithDirtyFile: "Save cancelled. The file still has unsaved changes.",
      edit: "Edit",
      legacyConfirmUnavailable:
        "OnlyOffice built-in format confirmation is not loaded. Refresh the page or restart the dev server and try again.",
      localPreviewFailed: "Failed to preview Office file locally.",
      openLimitReached:
        "You can open up to 12 Office documents at once. Close an Office tab and try again.",
      manageResources: "Manage Office resources",
      prepareResources: "Prepare and open",
      resourcesNotReady: "Office resources are not ready for an editor.",
      resourcePreparationClose: "Cancel Office resource preparation",
      resourcePreparationDescription: (size: string) =>
        `Opening this document requires downloading and verifying ${size} of Office resources. The document will open automatically when ready.`,
      resourcePreparationTitle: "Prepare Office resources",
      localPreviewTimeout: "Local Office preview timed out. Close the tab and try again.",
      modeSwitch: "Office mode switcher",
      noSaveAccess:
        "The user space does not have write access, so the Office file cannot be saved.",
      noSaveCopyAccess:
        "The user space does not have write access, so an Office file copy cannot be saved.",
      preview: "Preview",
      saveCopyFailed: "Failed to save Office file copy.",
      savedAs: (name: string) => `Saved as ${name}`,
      savedAsCopy: (name: string) => `Saved copy as ${name}`,
      savedAsAndDeletedOriginal: (nextName: string, originalName: string) =>
        `Saved as ${nextName} and deleted ${originalName}`,
      savedAsButDeleteOriginalFailed: (nextName: string, originalName: string, message: string) =>
        `Saved as ${nextName}, but failed to delete original ${originalName}: ${message}`,
      saveFailed: "Save failed",
      saveFileFailed: "Failed to save Office file.",
      saving: "Saving...",
      savedToUserSpace: "Saved to user space",
      title: (mode: "edit" | "preview", name: string) => `Local Office ${mode} ${name}`,
    },
    pdfPreviewTitle: (name: string) => `PDF preview ${name}`,
    fileMovedOrMissing: (name: string) => `“${name}” isn’t available.`,
    previewFailed: "File preview failed",
    previewTab: (title: string) => `Switch preview ${title}`,
    previewEntry: (name: string) => `Preview ${name}`,
    readonly: "Read-only",
    readwrite: "Read/write",
    rename: {
      aria: (name: string) => `Rename ${name}`,
      extensionChangeTitle: "Change file extension?",
      extensionChangeDescription: (currentName: string, nextName: string) =>
        `“${currentName}” will be renamed to “${nextName}”. Changing the extension may prevent the file from opening correctly.`,
      extensionChangeConfirm: "Change anyway",
    },
    runtimeErrors: {
      absolutePathUnsupported: "User-space operations do not allow absolute paths.",
      checkoutChanged:
        "The original user-space file changed after checkout. Check it out again before checking in.",
      checkoutTimestampChanged:
        "The original user-space file timestamp changed after checkout. Check it out again before checking in.",
      commitAuthorizationFailed: "User-space checkin write authorization failed.",
      commitLeaseMissing: "User-space checkin write authorization did not return a valid lease.",
      copyCleanupFailed:
        "The copy did not finish and some destination copies could not be removed. Check the destination folder manually.",
      copyFolderIntoSelf: (name: string) =>
        `Cannot copy "${name}" into itself or one of its subfolders.`,
      copySelectionEmpty: "There are no items to copy.",
      duplicateFolderUnsupported: "Folder duplication is not supported yet.",
      entryExists: (path: string) => `User-space entry already exists: ${path}`,
      hiddenEntryUnsupported:
        "User space hides dot-prefixed files and folders by default; enable display or search in personal settings.",
      idbBlocked: "The user-space database is blocked by another tab.",
      idbOpenFailed: "Failed to open the user-space database.",
      mountNotFound: (_mountId: string) => "User space is not authorized in this browser.",
      mountNameConflict: (name: string) => `The user space name “${name}” is already in use.`,
      batchTooLarge: (max: number) => `Process at most ${max} items at a time.`,
      moveCleanupFailed:
        "The move did not finish. The originals remain, but some destination copies may need to be removed manually.",
      moveFolderIntoSelf: (name: string) =>
        `Cannot move "${name}" into itself or one of its subfolders.`,
      moveSameParent: "The selected items are already in the destination folder.",
      moveSelectionEmpty: "There are no items to move.",
      moveSourceChanged: (path: string) =>
        `"${path}" changed while it was being copied, so the operation was canceled.`,
      readwriteRequired: (name: string) =>
        `User space "${name}" is read-only. Switch to read/write before modifying files.`,
      renameFolderUnsupported:
        "Folder rename is not supported yet. Create a new folder first, then move specific files.",
      sha256Unsupported:
        "This browser does not support the SHA-256 check required for user-space transfer.",
      unsupportedOperation: (operation: string) => `Unsupported user-space operation: ${operation}`,
      uniqueCopyNameFailed: "Could not generate an available copy file name.",
    },
    saveFailed: "Save failed",
    selectSpace: "Space switcher",
    setAccess: (name: string, access: "readonly" | "readwrite") =>
      `Set ${name} to ${access === "readonly" ? "read-only" : "read/write"}`,
    switchMount: (name: string) => `Switch user space folder, current ${name}`,
    switchConfirm: {
      title: "Switch user space folder?",
      description: (name: string, count: number) =>
        count > 0
          ? `Switching to ${name} will close ${count} open file preview${count === 1 ? "" : "s"} from the current folder. Unsaved changes will be lost.`
          : `Switch to ${name}?`,
      continueSwitch: "Continue switching",
    },
    toggleDirectory: (expanded: boolean, name: string) =>
      `${expanded ? "Collapse" : "Expand"} ${name}`,
    toggleMount: (expanded: boolean, name: string) =>
      `${expanded ? "Collapse" : "Expand"} ${name} user space`,
    syncIndex: "Sync space index",
    syncIndexFor: (name: string) => `Sync ${name} space index`,
    textSaveAction: {
      edit: "Edit",
      partial: "Only part of the file is loaded",
      readonly: "User space is read-only",
      save: "Save",
    },
    textSaveErrors: {
      fileTooLarge:
        "The file is too large. Only part of it is loaded, so it cannot be saved directly.",
      tabMissing: "Preview tab does not exist.",
      textReadFailed: "Failed to read file text.",
      unsupportedType: "This file type does not support text saving.",
    },
    truncatedNotice: (name: string, size: string) => `Showing only the first ${size} of ${name}.`,
    unmount: "Unmount",
    unmountFor: (name: string) => `Unmount ${name}`,
    unmountConfirm: {
      title: "Remove user space folder?",
      description: (name: string) =>
        `Remove “${name}” from this session. Local files won't be deleted.`,
      confirm: "Remove folder",
    },
    unsupportedPreview: "This file type cannot be previewed. You can open it with a local app.",
    unsavedClose: {
      titleMany: (count: number) => `Close ${count} unsaved files?`,
      titleOne: "Close unsaved file?",
      descriptionMany: (count: number) =>
        `${count} files have unsaved changes. Continuing will discard those changes.`,
      descriptionOne: (name: string) =>
        `${name} has unsaved changes. Continuing will discard them.`,
      continueClose: "Continue closing",
    },
    userSpace: "User space",
    validation: {
      emptyName: "Name cannot be empty.",
      hiddenName: "Dot-prefixed names are hidden by default; enable display in personal settings.",
      invalidCharacters: "Name contains invalid characters.",
      invalidDots: "Name cannot be . or ..",
      pathSeparator: "Name cannot contain path separators.",
      tooLong: "Name is too long.",
    },
    videoPreviewTitle: (name: string) => `Video preview ${name}`,
    workspaceSidebar: "Workspace file sidebar",
    workspaceTree: "Workspace file tree",
    workspaceTreeLabel: "User-space file tree",
    unsupportedActions: {
      duplicateFolderPending:
        "This version supports file duplication first. Folder duplication will be added later.",
      pasteFolderInsideSelf: (name: string) =>
        `Cannot paste "${name}" into itself or one of its subfolders.`,
      pasteSameMountOnly: "This version only supports copy and paste inside the same user space.",
      renameFolderPending:
        "This version supports file rename first. Folder rename will be added later.",
    },
  },
} satisfies DeepPartialUiCopy<UiCopy>;
