export const zhCNCopy = {
  browserBridge: {
    title: "Chrome 浏览器桥接",
    trigger: "Chrome 浏览器桥接",
    connected: "已连接",
    waiting: "等待扩展连接",
    stopped: "服务未启动",
    starting: "正在启动",
    unavailable: "运行组件未就绪",
    failed: "连接异常",
    description: "让 Agent 通过结构化 CDP 操作你授权的 Chrome 页面。",
    connectedDescription: "Chrome 扩展已连接，Agent 可以通过语义快照执行页面操作。",
    waitingDescription: "桥接服务已启动。请在 Chrome 中加载扩展，连接后再执行验证。",
    stoppedDescription: "先启动本地桥接服务，再在 Chrome 中加载扩展。",
    unavailableDescription: "请先构建固定版本的 agent-browser 运行组件。",
    errorDescription: "桥接服务暂时不可用，请刷新状态或重新启动。",
    runtime: "运行组件",
    daemon: "桥接服务",
    extension: "Chrome 扩展",
    ready: "就绪",
    online: "在线",
    offline: "离线",
    version: "版本",
    source: "源码版本",
    port: "端口",
    tabs: (count: number) => `${count} 个标签页`,
    sessions: (count: number) => `${count} 个 Agent 会话`,
    connectedProfiles: (count: number) => `${count} 个 Chrome 配置已连接`,
    setupTitle: "首次连接",
    stepOne: "打开 chrome://extensions 并开启开发者模式。",
    stepTwo: "选择“加载已解压的扩展程序”，然后加载下方目录。",
    stepThree: "保留要操作的页面打开，回到这里执行连接验证。",
    extensionPath: "扩展目录",
    copyPath: "复制扩展目录",
    pathCopied: "扩展目录已复制",
    start: "启动桥接",
    startingAction: "启动中...",
    verify: "验证连接",
    verifying: "验证中...",
    verifySuccess: (durationMs: number) => `连接验证成功（${durationMs} ms）`,
    refresh: "刷新状态",
    close: "关闭",
    missingArtifacts: (items: string) => `缺少：${items}`,
    controlTitle: "当前会话控制权",
    agentControl: "Agent 正在控制",
    takeoverPending: "正在移交给你",
    humanControl: "你正在控制",
    resumingControl: "正在交还给 Agent",
    stoppingControl: "正在停止浏览器控制",
    stoppedControl: "浏览器控制已停止",
    uncertainControl: "控制状态需要确认",
    controlEpoch: (epoch: number) => `控制轮次 ${epoch}`,
    takeOver: "接管浏览器",
    takingOver: "接管中...",
    resumeControl: "交还给 Agent",
    resumingControlAction: "交还中...",
    stopControl: "停止浏览器控制",
    stoppingControlAction: "停止中...",
    handoffLabel: "告诉 Agent 你做了什么",
    handoffPlaceholder: "例如：我已完成登录并选择了目标账号。",
    handoffDescription: "交还控制权后，Agent 会先重新读取页面，再继续操作。",
    pendingActionRisk: "中断确认未返回；请先检查页面，避免重复提交或重复点击。",
    privacyNotice:
      "Agent 可能读取当前授权页面的结构、文本和必要截图。控制状态不会展示页面网址或正文。",
    selectSession: "选择会话后才能管理浏览器控制权。",
  },
  common: {
    archive: "归档",
    archiveChat: "归档会话",
    attachImage: "添加图片",
    attachImages: "添加图片",
    backend: "后端",
    cancel: "取消",
    close: "关闭",
    conversation: "会话",
    create: "创建",
    delete: "删除",
    deleting: "删除中",
    dismiss: "忽略",
    edit: "编辑",
    chatActions: "会话操作",
    hide: "隐藏",
    listSeparator: "、",
    loading: "加载中...",
    messageInput: "消息输入框",
    model: "模型",
    paste: "粘贴",
    pasteClipboard: "从剪贴板粘贴",
    preview: "预览",
    processing: "处理中...",
    removeImage: "移除图片",
    reload: "重新加载",
    retry: "重试",
    rename: "重命名",
    restore: "恢复",
    save: "保存",
    saving: "保存中",
    search: "搜索",
    selectModel: "选择模型",
    sendMessage: "发送消息",
    showDetails: "查看详情",
    skipToMainContent: "跳到主要内容",
    text: "文本",
    stopGeneration: "停止生成",
    switchModel: "切换模型",
    taskDescription: "任务描述",
    user: "用户",
    currentModel: (model: string) => `当前模型：${model}`,
    removeNamedItem: (name: string) => `移除 ${name}`,
  },
  app: {
    checkingAuth: "正在检查登录状态...",
    description: "一站式Paperwork Agent工作台",
    documentTitle: "一站式Paperwork Agent工作台",
    enteringWorkbench: "正在进入Agent工作台...",
    enterWorkbenchFailed: "进入工作台失败",
    restoringWorkbench: "正在恢复Agent工作台...",
    syncingAccountSession: "正在同步账号会话...",
  },
  apps: {
    title: "Apps",
    description: "将 Agent 结果发布到你的 Cloudflare 账户，或创建一次性 Temporary Account 预览。",
    backToWorkbench: "返回工作台",
    filterLabel: "App 列表范围",
    filters: {
      currentSession: "当前会话",
      mine: "我的",
      tenant: "租户",
    },
    refresh: "刷新 Apps",
    loading: "正在加载 Apps...",
    loadFailed: "Apps 加载失败",
    retry: "重新加载",
    empty: {
      currentSessionTitle: "当前会话还没有 App",
      currentSessionDescription:
        "让 Agent 从 Agent Space 构建应用后，在这里选择 Temporary 或 BYOC 部署。",
      mineTitle: "你还没有 App",
      mineDescription: "从任意 Agent 会话构建的应用都会集中显示在这里。",
      tenantTitle: "当前租户还没有 App",
      tenantDescription: "租户成员构建并关联的应用会显示在这里。",
    },
    noCurrentSession: "当前没有可用于筛选的会话。",
    loadMore: "加载更多",
    screenshotAlt: (name: string) => `${name} 的应用截图`,
    screenshotPending: "预览就绪后会显示截图",
    owner: "所有者",
    updatedAt: (date: string) => `更新于 ${date}`,
    sourceSession: "来源会话",
    stableUrl: "稳定 URL",
    urlNotReady: "Cloudflare URL 尚未就绪",
    version: (number: number) => `版本 ${number}`,
    status: {
      building: "构建中",
      needs_action: "需要操作",
      deploying: "部署中",
      preview: "临时预览",
      ready: "已就绪",
      failed: "失败",
      archived: "已归档",
    },
    phase: {
      building: "正在构建",
      awaiting_target: "等待选择部署目标",
      awaiting_oauth: "等待 Cloudflare OAuth",
      queued: "已排队",
      provisioning: "正在准备 Cloudflare 资源",
      deploying: "正在部署",
      temporary_ready: "Temporary 预览已就绪",
      claim_pending: "等待认领 Temporary Account",
      verifying_claim: "正在验证认领账户",
      ready: "部署已就绪",
      expired: "Temporary 预览已过期",
      failed: "部署失败",
      cancelled: "部署已取消",
    },
    targetKind: {
      unassigned: "未选择",
      temporary: "Temporary Account",
      byoc: "Cloudflare BYOC",
    },
    open: "打开 App",
    copyUrl: "复制 URL",
    urlCopied: "App URL 已复制",
    preview: "预览 App",
    manage: "管理 App",
    detailsTitle: (name: string) => `管理 ${name}`,
    detailsDescription:
      "选择 Cloudflare 部署目标，查看部署阶段，并管理 Temporary 认领或 OAuth BYOC。",
    closeDetails: "关闭 App 管理面板",
    overview: "概览",
    deploymentTarget: "部署目标",
    currentDeployment: "当前部署",
    deploymentHistory: "部署历史",
    deploymentsEmpty: "暂无部署记录",
    currentVersion: "当前版本",
    rollback: "回滚到此版本",
    rollingBack: "正在回滚...",
    rollbackSucceeded: "已创建回滚部署，请选择 Cloudflare 目标",
    deploymentEvents: "部署事件",
    deploymentEventsEmpty: "暂无部署生命周期事件",
    chooseTarget: "选择 Cloudflare 部署目标",
    chooseTargetDescription:
      "Temporary 适合一次性预览；永久部署使用你通过 OAuth 连接的 Cloudflare 账户。",
    deploymentTargetsLoading: "正在读取可用的 Cloudflare 部署目标...",
    deploymentTargetsConfigUnavailable:
      "无法确认当前服务器启用的 Cloudflare 部署目标，已阻止提交。请返回开发会话后重试。",
    deploymentTargetsUnavailable:
      "当前服务器未启用 Temporary Account 或 OAuth BYOC 部署。请返回开发会话，稍后重试或联系管理员。",
    deploymentTargetsUnavailableAction: "返回开发会话",
    temporaryTarget: "Temporary 预览",
    byocTarget: "OAuth BYOC",
    temporaryDescription:
      "Temporary Account 仅支持无状态 Worker 与 Static Assets，通常约 60 分钟后过期，且每位未连接用户只能申请一次。",
    byocDescription:
      "Piwork 只会使用 OAuth 授权的所选账户，并按 App 清单部署普通 Cloudflare Worker。",
    acceptCloudflareTerms: "确认接受 Cloudflare 服务条款",
    acceptCloudflarePrivacy: "确认接受 Cloudflare 隐私政策",
    acceptTermsPrefix: "我已阅读并同意",
    acceptPrivacyPrefix: "我已阅读并同意",
    cloudflareTerms: "Cloudflare 服务条款",
    cloudflarePrivacy: "Cloudflare 隐私政策",
    cloudflareAccount: "Cloudflare 账户",
    selectCloudflareAccount: "选择已连接账户",
    cloudflareAccountOption: (name: string, id: string) => `${name}（${id}）`,
    noCloudflareConnection: "还没有可用的 Cloudflare OAuth 连接。",
    additionalOAuthPermissionsRequired: (permissions: string[]) =>
      `所选连接缺少此 App 所需权限（${permissions.join("、")}）。请重新连接 Cloudflare 完成增量授权。`,
    connectCloudflare: "连接 Cloudflare 账户",
    connectingCloudflare: "正在前往 Cloudflare...",
    deployToTarget: "部署到此目标",
    selectingTarget: "正在提交部署...",
    targetSelected: "部署目标已提交",
    turnstile: {
      label: "Cloudflare Turnstile 验证",
      loadingConfig: "正在读取 Temporary Account 安全配置...",
      configUnavailable: "Turnstile 配置不可用，暂时不能创建 Temporary 预览。",
      loading: "正在加载 Cloudflare Turnstile 验证...",
      verified: "Cloudflare Turnstile 验证已完成。",
      failed: "Cloudflare Turnstile 验证失败或已过期，请重新验证。",
      retry: "重新验证",
    },
    deploymentFailed: "Cloudflare 部署失败",
    oauthConnected: "Cloudflare 账户已连接，请重新打开 App 详情选择账户。",
    oauthCancelled: "Cloudflare OAuth 已取消，尚未连接或恢复任何部署。",
    oauthAccountMismatch:
      "OAuth 授权账户与已认领 Temporary Account 不一致。Piwork 未认领、未恢复部署。请选择认领该预览的账户；如需使用另一账户，请重新部署。",
    chooseClaimedAccount: "重新选择已认领账户",
    redeployToAnotherAccount: "用另一账户重新部署",
    retryOAuth: "重新连接 Cloudflare",
    temporaryExpired:
      "Temporary 预览或认领链接已过期。请创建新的 Temporary 预览，或改用 OAuth BYOC。",
    createNewTemporaryPreview: "创建新的 Temporary 预览",
    retryDeployment: "返回开发会话并重新部署",
    previewExpiresIn: (remaining: string) => `预览剩余时间：${remaining}`,
    claimExpiresIn: (remaining: string) => `认领链接剩余时间：${remaining}`,
    countdown: {
      unavailable: "不可用",
      expired: "已过期",
      hoursMinutes: (hours: number, minutes: number) => `${hours} 小时 ${minutes} 分钟`,
      minutesSeconds: (minutes: number, seconds: number) => `${minutes} 分 ${seconds} 秒`,
    },
    claimTemporaryPreview: "在 Cloudflare 认领此预览",
    claimThenConnectCloudflare: "认领后连接 Cloudflare",
    claimRequiresByoc:
      "当前 Temporary 预览仍可使用；认领并继续由 Piwork 管理需要启用 Cloudflare BYOC。",
    claimOwnerOnly: "只有创建此 Temporary 预览的所有者可以打开认领链接。",
    claimThenOAuth: "认领后仍需用同一 Cloudflare 账户完成 OAuth，Piwork 才能继续部署。",
    workerDomain: {
      title: "Worker Custom Domain",
      description:
        "为已就绪的 BYOC Worker 绑定同一 Cloudflare 账户中的精确域名。这里只使用普通 Workers Custom Domains。",
      defaultUrlRetained: "workers.dev 默认 URL 会永久保留，绑定或解绑域名都不会移除它。",
      connection: "Cloudflare 连接",
      selectConnection: "选择部署该 Worker 的连接",
      zone: "Cloudflare Zone",
      loadingZones: "正在加载可用 Zone...",
      selectZone: "选择 Active Zone",
      noActiveZones: "此连接没有可用的 Active Zone，或 OAuth 未授予 Zone 访问权限。",
      hostname: "精确 hostname",
      hostnameDescription: "请输入所选 Zone 的完整 hostname；不支持 wildcard。",
      hostnamePlaceholder: "app.example.com",
      wildcardNotAllowed: "Worker Custom Domain 不允许 wildcard hostname。",
      invalidHostname: "请输入属于所选 Active Zone 的精确 hostname。",
      status: {
        pending: "正在绑定",
        active: "已生效",
        failed: "绑定失败",
        removing: "正在解绑",
      },
      sslStatus: {
        pending_validation: "证书等待验证",
        pending_issuance: "证书正在签发",
        active: "证书已生效",
        failed: "证书失败",
      },
      detachCertificateImpact:
        "解绑只移除 Worker 的 hostname 路由，不会删除 Cloudflare 自动签发的 Advanced Certificate。",
      confirmImpact: "确认 Worker Custom Domain 影响",
      confirmAttachImpact:
        "我确认此精确 hostname 将路由到该 Worker，并了解现有 DNS 或路由可能受到影响。",
      confirmDetachImpact:
        "我确认解绑将停止此 hostname 的 Worker 路由；workers.dev URL 与自动签发的 Advanced Certificate 会保留。",
      attach: "绑定 Worker Custom Domain",
      attaching: "正在绑定...",
      attached: "Worker Custom Domain 已提交绑定",
      detach: "解绑 Worker Custom Domain",
      detaching: "正在解绑...",
      detached: "Worker Custom Domain 已提交解绑",
    },
    continueDevelopment: "继续开发",
    continuingDevelopment: "正在打开开发会话...",
    archive: "归档并解除关联",
    archiving: "正在归档...",
    archiveConfirm: (name: string) =>
      `归档「${name}」并从 Piwork 解除关联？这不会删除或停用你的 Cloudflare Worker、域名或其他资源。`,
    archived: "App 已归档；Cloudflare 资源保持不变",
    archivedAt: (date: string) => `已于 ${date} 归档；Cloudflare 资源未删除`,
    archivedResourcesRemain: "归档只解除 Piwork 关联，不会删除 Cloudflare 资源。",
    unarchive: "取消归档",
    unarchiving: "正在取消归档...",
    unarchived: "App 已取消归档",
    previewTitle: (name: string) => `${name} App 预览`,
    previewDescription: "预览直接运行在用户的 Cloudflare 来源中，不会接收 Piwork 登录 Cookie。",
    closePreview: "关闭 App 预览",
    previewUnsafe: "该预览 URL 不是受支持的独立 HTTPS Cloudflare 来源。",
    previewLoading: "正在加载 App 预览...",
    actionFailed: "App 操作失败",
  },
  piRuntime: {
    connectionTimeout: "等待 Pi 会话连接超时。",
    invalidSessionCreateResponse: "会话服务返回了无效的 Pi 运行时数据。",
    noModels: "当前 Agent 没有可用模型，请检查模型策略、凭据和网络策略。",
    sessionCreationFailed: "Pi 会话创建失败。",
    sessionCreateStreamEnded: "Pi 会话创建数据流在返回结果前已结束。",
    thinkingLevel: "推理强度",
    thinkingLevels: {
      off: "关闭",
      minimal: "极低",
      low: "低",
      medium: "中",
      high: "高",
      xhigh: "极高",
      max: "最大",
    },
    reasoningModelDescription: "支持推理等级的 Pi 模型",
    standardModelDescription: "Pi 模型",
    toolStatus: {
      started: "已开始",
      running: "运行中",
      completed: "已完成",
      failed: "失败",
      cancelled: "已取消",
    },
  },
  interaction: {
    askTitle: "需要你的回答",
    planTitle: "执行计划确认",
    submit: "提交回答",
    freeTextLabel: "自由输入",
    freeTextPlaceholder: "输入你的回答…",
    freeTextOption: "自由输入",
    finishSelection: "完成选择",
    executePlan: "执行计划",
    continuePlanning: "继续规划",
    refinePlan: "细化计划",
    submitRefinement: "提交细化要求",
    refinementLabel: "计划细化要求",
    refinementPlaceholder: "说明需要调整或补充的内容…",
    sessionClosed: "会话连接已关闭，请重新连接后再试。",
    timedOut: "交互已超时",
  },
  chat: {
    activeGroup: "活跃",
    archivedSessions: "归档会话",
    archiveSession: (title: string) => `归档 ${title}`,
    archived: {
      bulkDelete: "删除",
      bulkDeleteFailed: "删除所选会话失败",
      bulkDeleteConfirm: (count: number) =>
        `删除 ${count} 个归档会话？此操作会删除会话目录和历史，无法恢复。`,
      bulkRestore: "恢复",
      bulkRestoreFailed: "批量恢复归档会话失败",
      createdAt: (date: string) => `创建 ${date}`,
      delete: "删除",
      deleteFailed: "删除失败",
      deleteOneConfirm: (title: string) =>
        `删除「${title}」？此操作会删除会话目录和历史，无法恢复。`,
      empty: "暂无归档会话",
      loading: "正在加载归档会话...",
      loadFailed: "归档会话加载失败",
      restore: "恢复",
      restoreFailed: "恢复归档会话失败",
      selectAll: "选择全部归档会话",
      selectedCount: (count: number) => `已选择 ${count} 个`,
      selectSession: "选择会话",
      selectSessionLabel: (title: string) => `选择归档会话 ${title}`,
      title: "归档会话",
      unknownAgent: "默认 Agent",
      archivedAt: (date: string) => `归档 ${date}`,
    },
    assistantAndSessionSelector: "Agent和会话级联选择器",
    backendTheme: {
      system: { label: "系统", description: "跟随系统外观" },
      light: { label: "浅色", description: "固定浅色界面" },
      dark: { label: "深色", description: "固定深色界面" },
    },
    createSession: "创建会话",
    selectSession: "选择会话",
    createAgentSession: (name: string) => `创建${name}会话`,
    deleteArchivedManyConfirm: (count: number) =>
      `删除 ${count} 个归档会话？此操作会删除会话目录和历史，无法恢复。`,
    deleteArchivedOneConfirm: (title: string) =>
      `删除「${title}」？此操作会删除会话目录和历史，无法恢复。`,
    agentSelector: "选择Agent",
    errors: {
      preferencesLoadFailed: "偏好设置加载失败",
      preferencesSaveFailed: "偏好设置保存失败",
      renameFailed: "重命名失败",
      startAgentFailed: "启动Agent失败",
    },
    emptyState: {
      title: "我能为你做什么？",
      description: "挂载本地目录以协作处理文件，或直接描述需要Agent推进的任务。",
      mountUserSpace: "打开用户空间",
      summarizeDirectory: "查看并总结当前目录",
      createPlan: "为这个任务制定实现计划",
      blankTask: "从空白任务开始",
    },
    idleGroup: "闲置",
    loadMoreSessions: "加载更多会话",
    noSessionMessages: "暂无消息",
    noMessages: "暂无消息",
    noSessions: "暂无会话",
    now: "刚刚",
    preferencesPanel: {
      accountInfo: "账号信息",
      appearance: "外观与语言",
      close: "关闭",
      closeLabel: "关闭个人设置",
      fileDefaultOpenMode: "文件默认打开方式",
      labels: {
        displayName: "用户名",
        email: "邮箱",
        org: "组织",
        roles: "角色",
        username: "用户名",
      },
      title: "个人设置",
      office: {
        title: "Office 文件默认打开方式",
        preview: "预览",
        edit: "编辑",
      },
      officeResources: {
        title: "Office 资源",
        description: "打开文档时自动准备所需资源，也可提前安装常用字体。",
        version: (version: string) => `OnlyOffice ${version}`,
        checking: "正在检查",
        updating: "正在更新",
        ready: "已就绪",
        incomplete: "未完整下载",
        updateAvailable: "有可用更新",
        paused: "已暂停",
        repairNeeded: "需要修复",
        error: "操作失败",
        statusUnavailable: "暂时无法读取资源状态",
        summary: (completed: number, total: number) => `${completed} / ${total} 个文件已缓存`,
        failedFiles: (count: number) => `${count} 个文件加载失败`,
        progressLabel: "Office 资源缓存进度",
        downloadProgress: (completed: string, total: string) => `正在下载 ${completed} / ${total}`,
        verifyProgress: (completed: string, total: string) => `正在校验 ${completed} / ${total}`,
        phases: {
          idle: "等待操作",
          planning: "正在规划",
          downloading: "正在下载",
          verifying: "正在校验",
          activating: "正在完成更新",
          repairing: "正在修复",
          paused: "已暂停",
        },
        categoryProgressLabel: (category: string) => `${category}缓存进度`,
        categories: {
          fonts: "字体",
          core: "通用运行时与 x2t",
          word: "Word",
          cell: "电子表格",
          slide: "演示文稿",
        },
        fontsTitle: "字体包",
        basicPreset: "准备基础资源",
        compatibilityPreset: "安装 Office 兼容字体",
        advanced: "高级资源与字体",
        packReady: "已安装",
        packOnDemand: "按需下载",
        storageNote: "资源保存在此浏览器中，不会占用 Piwork 工作区。",
        required: "必需",
        download: "下载",
        remove: "移除",
        downloadAll: "下载全部",
        checkAndRepair: "检查并修复",
        pause: "暂停",
        resume: "继续",
        retry: "重试",
        reopenHint: "字体变更将在重新打开 Office 文档后生效。",
        failedResource: (path: string) => `受影响资源：${path}`,
        errors: {
          statusUnavailable: "Office 资源状态不可用，请检查网络后重试。",
          offline: "网络已断开，联网后可继续。",
          network: "资源下载失败，请重试。",
          timeout: "资源下载超时，请继续或重试。",
          integrity: "资源完整性校验失败，请修复受影响的资源。",
          quota: "浏览器存储空间不足，请释放空间后重试。",
          manifest: "Office 资源清单无效。",
          incompatible: "Office 资源版本与当前 Piwork 不兼容。",
          storage: "无法保存 Office 资源安装状态。",
          aborted: "Office 资源操作已取消。",
          insufficientStorage: (available: string, required: string) =>
            `浏览器存储空间不足：可用 ${available}，需要 ${required}。请释放空间或退出无痕模式。`,
        },
      },
      filePanel: {
        title: "文件面板",
      },
      nativeHelper: {
        title: "原生助手",
        description:
          "连接 Piwork Helper，让文件使用 macOS 的预览、打开、打印、导出、分享与本机编辑能力。",
        checking: "正在检查",
        unsupported: "当前系统不支持",
        notInstalled: "未安装",
        offline: "已安装，但未连接",
        incompatible: "版本不兼容",
        connected: "已连接",
        updateAvailable: "有可用更新",
        version: (version: string) => `当前版本 ${version}`,
        latestVersion: (version: string) => `最新版本 ${version}`,
        capabilities: (count: number) => `${count} 项原生能力可用`,
        refresh: "刷新状态",
        copyInstallCommand: "复制安装命令",
        copyUpgradeCommand: "复制升级命令",
        copied: "命令已复制",
        lastError: (message: string) => `最后错误：${message}`,
      },
      userSpace: {
        showHiddenEntries: "显示隐藏文件",
        showHiddenEntriesDescription: "让用户空间文件树和 tree 显示 . 开头的路径。",
        title: "用户空间",
      },
    },
    preferences: "个人设置",
    reloadSessions: "重新加载会话",
    runningGroup: "运行",
    searchSession: "搜索会话",
    sessionName: "会话名称",
    sessionGroupLabel: (label: string) => `${label}会话`,
    sessionSelector: "选择会话",
    renameSession: (title: string) => `重命名 ${title}`,
    renameSessionEmpty: "请输入会话名称",
    startingAgentSession: (name: string) => `正在启动${name}Agent...`,
    agentSessionStarted: "Agent会话已启动",
    sessionTime: {
      minutesAgo: (value: number) => `${value}分钟前`,
      hoursAgo: (value: number) => `${value}小时前`,
      daysAgo: (value: number) => `${value}天前`,
    },
    userDetails: "用户详情",
    userMenu: {
      admin: "管理后台",
      destroyAndLogout: "销毁工作台并退出",
      keyboardShortcuts: "键盘快捷键",
      logout: "退出登录",
      theme: "外观",
      themeOption: (label: string) => `外观：${label}`,
    },
    keyboardShortcuts: {
      title: "键盘快捷键",
      close: "关闭键盘快捷键",
      sections: {
        workspace: "工作区",
        chat: "聊天",
      },
      actions: {
        sessionSearch: "搜索会话",
        fileSearch: "搜索文件",
        toggleFilePreview: "展开或折叠文件预览面板",
        toggleSessionPanel: "展开或折叠会话区域",
        toggleSpacePanel: "展开或折叠用户｜Agent空间面板",
        newLine: "换行",
        sendMessage: "发送消息",
        togglePlanMode: "切换计划模式",
        openShortcutReference: "打开键盘快捷键",
      },
      conditions: {
        filePreviewOpen: "仅在文件预览面板打开时可用",
      },
      keys: {
        command: "⌘",
        b: "B",
        control: "Ctrl",
        shift: "Shift",
        enter: "Enter",
        f: "F",
        k: "K",
        p: "P",
        slash: "/",
        tab: "Tab",
        u: "U",
      },
    },
    waitingReply: "等待回复",
  },
  composer: {
    connectionUnavailable: "工作台连接已断开，恢复连接后即可继续发送。",
    defaultFileRefMessage: "请查看我引用的用户空间文件。",
    defaultImageMessage: "请查看我附加的图片。",
    dropImages: "松开即可添加图片",
    planLabel: "计划",
    previewReferencedFile: (name: string) => `预览引用文件 ${name}`,
    shortcuts: "Enter 换行 · Shift+Enter 发送 · Shift+Tab 切换计划模式",
  },
  appError: {
    recoverPageDescription: "请重新加载页面以恢复。错误已上报。",
    runtimeErrorTitle: "发生运行时错误",
    sectionLoadFailed: (label?: string) => (label ? `${label}加载失败` : "分区加载失败"),
  },
  agentGovernance: {
    approvedSkills: "已审批 Skills",
    controlPlane: "Agent控制面",
    defaultDescription: "配置知识、Skills、MCP 与网络边界，然后发布不可变版本。",
    draftOnly: "仅草稿",
    empty: "此租户还没有可用Agent。个人租户迁移后会自动创建不可删除的通用Agent。",
    governance: "Agent治理",
    instructions: "运行指令",
    instructionsHint: "保存不会影响已发布版本",
    instructionsPlaceholder: "描述这个Agent的职责、工作方式和边界……",
    knowledgeDirectories: "只读知识目录",
    mcpConnections: "MCP 连接",
    networkPolicies: "网络策略",
    policyHint:
      "资源引用必须属于当前租户；未扫描或未审批的 Skill、已撤销 MCP、跨租户目录和无效网络策略会在发布时被拒绝。",
    publish: "发布版本",
    published: "已发布",
    publishedMessage: (version: number) => `版本 v${version} 已发布；新会话将固定使用该版本。`,
    refresh: "刷新Agent",
    saveDraft: "保存草稿",
    savedMessage: "草稿已保存，运行中的会话不会受影响。",
    selectAgent: "选择一个Agent查看治理配置",
  },
  diff: {
    noChanges: "没有更改",
  },
  agents: {
    displayName: (name: string) => `${name}Agent`,
    items: {
      agent: {
        name: "Agent",
        role: "文档、表格、演示文稿与日常办公支持",
        tone: "清晰可靠",
      },
    },
  },
  login: {
    authFailed: "认证失败",
    brand: "派活工作台",
    confirmPassword: "确认密码",
    connectAuthService: "正在连接认证服务...",
    createAccount: "创建账号",
    disabledRegistration: "当前系统已关闭自主注册",
    email: "邮箱",
    login: "登录",
    loginServiceUnavailable: "登录服务暂不可用，请联系系统管理员。",
    missingSignInFields: "请输入邮箱和密码",
    missingSignUpFields: "请输入姓名、邮箱和两次密码",
    missingEnterpriseName: "请输入企业或组织名称。",
    missingTeamName: "请输入团队名称。",
    name: "姓名",
    password: "密码",
    passwordMismatch: "两次输入的密码不一致",
    registrationClosed: "注册已关闭",
    registration: {
      enterprise: { description: "面向组织治理和分级管理的使用场景", title: "企业组织" },
      personal: { description: "面向个人任务和本地私有目录的使用场景", title: "个人" },
      team: { description: "面向小团队协作和共享流程的使用场景", title: "团队" },
    },
    privacyNote: "账号用于隔离本地工作台数据；模型凭据由平台按会话安全注入。",
    signInDescription: "登录后继续你的本地Agent会话。",
    signUpDescription:
      "选择适合现在的协作方式。高级 Agent、知识库和权限可以稍后配置，注册只需约一分钟。",
    signUpTitle: "建立你的工作空间",
    signUp: "注册",
    switchToLogin: "切换到登录",
    switchToSignUp: "切换到注册",
    title: "Agent工作台",
    usageMode: "使用方式",
    teamName: "团队名称",
    teamNamePlaceholder: "例如：产品研发团队",
    organizationName: "企业或组织名称",
    organizationNamePlaceholder: "例如：星河科技",
  },
  folderPicker: {
    clearFilter: "清除筛选",
    close: "关闭",
    closeButton: "关闭",
    directoryBreadcrumb: "目录路径",
    dialogLabel: "选择文件夹",
    filterDirectories: "筛选目录",
    filterPlaceholder: "筛选...",
    loadDirectoryFailed: "无法加载目录",
    loadingDirectories: "正在加载目录",
    manualPath: "手动输入路径",
    navigate: "进入",
    navigateInto: (name: string) => `进入 ${name}`,
    noMatchingDirectories: "没有匹配的目录",
    noSubdirectories: "没有子目录",
    parent: "上级目录",
    recent: "最近使用",
    recentDirectories: "最近使用的目录",
    retry: "重试",
    select: "选择",
    selectButton: "选择",
    selectDirectory: (name: string) => `选择 ${name}`,
    subdirectories: "子目录",
    title: "选择文件夹",
    typeDirectoryPath: "输入目录路径",
  },
  message: {
    collapseThinking: "折叠 Thinking",
    expandThinking: "展开 Thinking",
    imageAttachmentAlt: "附件",
    noThinking: "暂无思考内容。",
    previewReferencedFile: (name: string) => `预览引用文件 ${name}`,
    showAll: "显示全部",
    showTail: "显示末尾",
    thinkingDone: "已思考",
    thinkingStreaming: "思考中",
    tailStatus: (shown: number, total: number) => `共 ${total} 行，显示最后 ${shown} 行`,
    totalLines: (count: number) => `${count} 行`,
  },
  messageFeed: {
    assistantStreaming: "助手正在输出回复",
    contextOrganizing: "正在整理上下文...",
    loadMore: (count: number) => `再加载 ${count} 条`,
    hiddenCount: (count: number) => `（已隐藏 ${count} 条）`,
    loadOlder: "加载更早会话记录",
    loadingOlder: "正在加载更早记录...",
    reloadSessionHistory: "重新加载会话记录",
    sessionHistoryLoadFailedRetry: "会话记录加载失败，点击重试",
    scrollToBottom: "回到底部",
    workStepsRunning: (count: number) => `${count} 个工作步骤正在运行`,
  },
  messageToc: {
    emptyMessage: "空消息",
    imageMessage: "图片消息",
    jumpToMessage: (ordinal: number, preview: string) => `跳转到第 ${ordinal} 条消息：${preview}`,
    label: "消息目录",
  },
  permission: {
    askUser: {
      customAnswer: "其他，输入你的回答",
      fallbackQuestion: "请确认下一步。",
      interruptQuestion: "忽略问题并中断工具",
      multipleChoice: "多选",
      next: "下一个",
      nextQuestion: "下一个问题",
      previous: "上一个",
      previousQuestion: "上一个问题",
      singleChoice: "单选",
    },
    exitPlan: {
      adjustPlaceholder: "否，请说明如何调整",
      continuePlanInstruction: "请继续规划并调整方案",
      continuePlanningPlaceholder: "否，请说明继续规划什么",
      exitAction: "退出计划模式",
      exitTitle: "退出计划模式？",
      implementAction: "是，实施此计划",
      implementTitle: "实施此计划？",
    },
    approvalDetailFallback: "继续之前需要你的批准。",
    approve: "批准",
    denyMessage: "用户已拒绝",
    hideDetails: "隐藏详情",
    interruptMessage: "工具已中断",
    planApprovalRequested: "请求批准计划",
    reject: "拒绝",
    requestedPermissions: "请求的权限",
    reviewNeeded: "需要审核",
    showDetails: "显示详情",
    suggestion: {
      addDirectories: (directory: string, scope: string) => `信任 ${directory}${scope}`,
      addRules: (rule: string, scope: string) => `批准“${rule}”${scope}`,
      always: "（始终）",
      fallback: (scope: string) => `批准${scope}`,
      forSession: "（本次会话）",
      setMode: (mode: string) => `批准并将模式设为“${mode}”`,
      tool: (tool: string, scope: string) => `批准 ${tool}${scope}`,
    },
    sessionClosed: "会话已关闭，请重新启用后再回答",
    submit: "提交",
  },
  pwaPlatform: {
    eyebrow: "桌面兼容性",
    titles: {
      mobile: "移动设备不受支持",
      safari: "Safari 不受支持",
      firefox: "Firefox 不受支持",
      other: "当前浏览器不受支持",
      "desktop-chromium": "当前浏览器不受支持",
    },
    descriptions: {
      mobile: "派活 是面向鼠标、键盘与多窗口工作流的桌面工作台，手机和平板设备不在支持范围内。",
      safari: "派活 依赖桌面 Chromium 的文件系统与安装能力，因此不支持 Safari。",
      firefox: "派活 依赖桌面 Chromium 的文件系统与安装能力，因此不支持 Firefox。",
      other: "当前环境不是受支持的桌面 Chromium 浏览器。",
      "desktop-chromium": "当前环境不是受支持的桌面 Chromium 浏览器。",
    },
    requirement: "请在桌面电脑上使用最新版 Chrome、Microsoft Edge 或其他 Chromium 浏览器。",
    matrixTitle: "支持范围",
    supported: "支持",
    unsupported: "不支持",
    desktopChromium: "桌面 Chrome / Edge / Chromium",
    safariFirefox: "Safari 与 Firefox",
    mobileDevices: "手机与平板设备",
    retry: "重新检测环境",
    installTitle: "把 派活 留在桌面",
    installBody: "安装后可从系统启动器打开独立工作台窗口。",
    install: "安装桌面应用",
    installing: "正在打开安装窗口…",
    updateTitle: "新版本已准备好",
    updateBody: "先保存正在编辑的文件，再更新并重新打开工作台。",
    update: "保存后更新",
    updating: "正在更新…",
    updateBlocked: "仍有未保存的文件，请保存后再更新。",
    updateFailed: "更新未能完成，请重新加载后重试。",
    offlineTitle: "当前处于离线状态",
    offlineBody: "会话和文件不会使用缓存数据；恢复连接后即可继续。",
    pwaUnavailableTitle: "此地址无法安装桌面应用",
    pwaUnavailableBody:
      "工作台仍可使用。若要安装，请通过 HTTPS、localhost 或 127.0.0.1 打开 派活。",
    swUnavailableBody: "当前 Chromium 环境禁用了 Service Worker，因此无法安装或使用断线页。",
    registrationErrorTitle: "桌面应用功能没有启动",
    registrationErrorBody: "Service Worker 注册失败。工作台仍可使用，重新加载后可再次尝试。",
    reload: "重新加载",
    dismiss: "暂不显示",
  },
  rbacAdmin: {
    add: "添加",
    allMembersCount: (count: number) => `全体成员 · 共 ${count} 人`,
    assignedCount: (count: number, noun: string) => `${count} ${noun}`,
    audit: {
      detail: "记录明细",
      empty: "暂无审计记录",
      matchedEmpty: "没有匹配的审计记录",
      recordCount: (filtered: number, total: number) => `${filtered} / ${total} 条记录`,
      recordId: (id: string) => `记录编号：${id}`,
      actorId: (id: string) => `操作者编号：${id}`,
      resourceId: (type: string, id: string | null | undefined) => `对象编号：${type}:${id}`,
      searchLabel: "搜索审计记录",
      searchPlaceholder: "搜索操作者、对象或动作",
      title: "审计",
      unknownActor: "未知用户",
      unknownTarget: "目标对象",
      actionSummary: {
        bootstrapAdmin: (target: string) => `将 ${target} 初始化为系统管理员`,
        denied: "尝试进入未授权的管理功能",
        departmentCreate: (target: string) => `创建了部门 ${target}`,
        departmentUpdate: (target: string) => `编辑了部门 ${target}`,
        departmentDelete: (target: string) => `删除了部门 ${target}`,
        departmentRolesReplace: (target: string) => `调整了部门 ${target} 的角色`,
        roleCreate: (target: string) => `创建了角色 ${target}`,
        roleUpdate: (target: string) => `编辑了角色 ${target}`,
        roleDelete: (target: string) => `删除了角色 ${target}`,
        rolePermissionsReplace: (target: string) => `调整了角色 ${target} 的权限`,
        userCreate: (target: string) => `创建了用户 ${target}`,
        userRolesReplace: (target: string) => `调整了成员 ${target} 的角色`,
        userDepartmentsReplace: (target: string) => `调整了成员 ${target} 的部门`,
        userPasswordReset: (target: string) => `重置了成员 ${target} 的密码`,
        systemSettingsUpdate: "调整了系统设置",
        fallback: (action: string) => `执行了 ${action}`,
        withActor: (actor: string, action: string) => `${actor} ${action}`,
      },
    },
    cancel: "取消",
    close: "关闭",
    closeDepartmentMenu: "关闭部门操作菜单",
    create: "创建",
    dashboard: {
      back: "返回工作台",
      loading: "正在加载管理数据...",
      noPermission: "没有管理后台权限",
      noPermissionDescription: "请联系管理员开通权限。",
      subtitle: "成员、部门、角色和审计",
      title: "权限管理",
    },
    delete: "删除",
    department: {
      addExistingUser: "添加已有用户",
      addUser: {
        duplicate: "该用户已在此部门中",
        inputPlaceholder: "输入姓名或邮箱",
        joined: "成员已加入部门",
        missing: "请输入目标用户",
        notFound: "未找到目标用户，请从联想结果中选择",
        searching: "搜索中...",
        targetUser: "目标用户",
        title: "添加用户到部门",
      },
      createChild: "新建子部门",
      createSuccess: "部门已创建",
      delete: "删除部门",
      deleteDescription: "删除前请输入部门全称。部门下仍有子部门或成员时，不能删除。",
      deleteSuccess: "部门已删除",
      edit: "编辑部门",
      emptyName: "部门名称不能为空",
      expand: "展开部门",
      collapse: "折叠部门",
      operation: (name: string) => `${name} 操作`,
      name: "部门名称",
      parent: "上级部门",
      parentLabel: (name: string) => `上级部门：${name}`,
      root: "根部门",
      roles: "部门角色",
      searchMembers: "搜索成员",
      selectFirst: "请先选择具体部门",
      selectPlaceholder: "请选择部门",
      sortOrder: "排序",
      tableTitle: "部门树",
      totalMembers: (count: number) => `共 ${count} 人`,
      typeConfirm: (name: string) => `输入「${name}」确认`,
      updateSuccess: "部门已保存",
    },
    description: "描述",
    edit: "编辑",
    member: {
      department: "部门",
      directRoles: "直接角色",
      edit: "编辑成员",
      editUser: (name: string) => `编辑 ${name}`,
      informationSaved: "成员信息已保存",
      loading: "正在加载成员...",
      matchedEmpty: "没有匹配的成员",
      name: "成员",
      permissions: "权限",
      roles: "角色",
      unassigned: "未分配",
      operations: "操作",
    },
    none: "无",
    noDescription: "无描述",
    noOptions: "暂无选项",
    pagination: {
      next: "下一页",
      previous: "上一页",
    },
    password: {
      emptyNew: "新密码不能为空",
      initial: "初始密码",
      emptyInitial: "初始密码不能为空",
      new: "新密码",
      reset: "重置密码",
      resetConfirm: "确认重置",
      resetSuccess: "密码已重置",
    },
    role: {
      create: "新建角色",
      createSuccess: "角色已创建",
      delete: "删除角色",
      deleteSuccess: "角色已删除",
      edit: "编辑角色",
      editRole: (name: string) => `编辑角色 ${name}`,
      emptyName: "角色名称不能为空",
      name: "角色名称",
      permissionCount: (count: number) => `${count} 项`,
      permissions: "权限",
      system: "系统",
      systemReadonly: "系统角色不可编辑",
      title: "角色权限",
      titleMeta: (roleCount: number, permissionCount: number) =>
        `${roleCount} 个角色，${permissionCount} 项权限`,
      updateSuccess: "角色已保存",
    },
    save: "保存",
    searchNameOrEmail: "搜索姓名或邮箱",
    searchUsersLabel: "搜索用户",
    settings: {
      registrationDisabled: "已关闭注册",
      registrationEnabled: "已开启注册",
      registrationLabel: "允许自主注册",
      registrationDescription: "关闭后，登录页不再提供注册入口。",
      subtitle: "管理系统的基础开关",
      title: "系统设置",
    },
    tabs: {
      audit: "审计",
      agents: "Agent治理",
      label: "权限管理分区",
      members: "成员与部门",
      roles: "角色权限",
      settings: "系统设置",
      users: "用户管理",
    },
    tagPicker: {
      add: "添加",
      duplicate: (label: string) => `${label} 已存在`,
      inputPlaceholder: "输入部门名称",
      missing: (title: string) => `请输入${title}`,
      notFound: (title: string) => `未找到${title.replace(/^所属/, "")}，请从联想结果中选择`,
      remove: (id: string) => `移除 ${id}`,
    },
    user: {
      confirmPassword: "确认密码",
      create: "新建用户",
      createSuccess: "用户已创建",
      createSubtitle: "创建成员账号并设置部门、角色",
      displayName: "姓名",
      emptyDisplayName: "姓名不能为空",
      emptyEmail: "邮箱不能为空",
      email: "邮箱",
      passwordMismatch: "两次输入的密码不一致",
    },
  },
  markdownEditor: {
    blockEdit: {
      textGroup: {
        label: "文本",
        text: "正文",
        h1: "一级标题",
        h2: "二级标题",
        h3: "三级标题",
        h4: "四级标题",
        h5: "五级标题",
        h6: "六级标题",
        quote: "引用",
        divider: "分割线",
      },
      listGroup: {
        label: "列表",
        bulletList: "无序列表",
        orderedList: "有序列表",
        taskList: "任务列表",
      },
      advancedGroup: {
        label: "插入",
        image: "图片",
        codeBlock: "代码块",
        table: "表格",
        math: "公式",
      },
    },
    codeMirror: {
      copy: "复制",
      edit: "编辑",
      hide: "隐藏",
      loading: "加载中...",
      noResult: "无结果",
      preview: "预览",
      searchLanguage: "搜索语言",
    },
    loadFailed: "Markdown 编辑器加载失败",
    imageBlock: {
      captionPlaceholder: "添加图片说明",
      confirm: "确认",
      inlineUpload: "上传",
      pasteLink: "或粘贴链接",
      uploadImage: "上传图片",
    },
    linkTooltip: {
      pasteLink: "粘贴链接...",
    },
    placeholder: "输入内容，或按 / 插入内容",
    topBar: {
      label: "Markdown 编辑工具栏",
      paragraph: "正文",
      stylePicker: "段落样式",
      actions: {
        bold: "加粗",
        italic: "斜体",
        strikethrough: "删除线",
        bulletList: "无序列表",
        orderedList: "有序列表",
        taskList: "任务列表",
        table: "表格",
        codeBlock: "代码块",
        quote: "引用",
        divider: "分割线",
      },
    },
  },
  session: {
    defaultName: "新聊天",
    launchFailed: "启动失败",
    openWorkbench: "正在打开工作台",
    prepareWorkbench: "正在准备工作台",
    startAgentFailed: "启动Agent失败",
  },
  timeline: {
    approved: "已批准",
    cancelled: "已取消",
    expandPlan: "展开计划",
    expandPlanContent: "展开计划内容",
    noThinking: "暂无思考内容。",
    noToolDetails: "没有可用的工具详情。",
    plan: "计划",
    subagent: "子 Agent",
    stopTask: "停止任务",
    stoppingTask: "正在停止…",
    task: "任务",
    thinking: "Thinking",
    thinkingDone: "已思考",
    thinkingStreaming: "思考中",
    planApprovalKeywords: {
      approved: ["批准"],
      rejected: ["驳回", "反馈", "拒绝"],
      cancelled: ["取消"],
      controlResult: ["驳回", "取消", "反馈"],
    },
    rejected: "已驳回",
    collapsePlan: "收起计划",
    unansweredAnswers: ["未回答", "等待回答"],
    waitingAnswer: "等待回答",
  },
  topBar: {
    language: "语言",
    languageOption: (label: string) => `语言：${label}`,
    languages: {
      zhCN: { label: "中文", description: "使用中文界面" },
      enUS: { label: "English", description: "使用英文界面" },
    },
    openUserMenu: "打开用户菜单",
    toggleSidebar: "切换侧边栏",
    userMenu: "用户菜单",
    workspace: "工作区",
  },
  toolExecution: {
    active: "进行中",
    workStepsRunning: (count: number) => `${count} 个工作步骤正在运行`,
  },
  toolSummary: {
    awaitingApproval: (count: number) => `${count} 个等待批准`,
    running: (count: number) => `${count} 个运行中`,
    stepsCompleted: (count: number, seconds: string) =>
      `${count} 个工作步骤已完成，耗时 ${seconds} 秒`,
    steps: (count: number) => `${count} 个步骤`,
    errors: (count: number) => `${count} 个错误`,
  },
  toolBlock: {
    actionLabels: {
      bash: "正在执行命令",
      read: "正在读取文件",
      write: "正在写入文件",
      edit: "正在编辑文件",
      ask: "正在等待回答",
      task: "正在协调任务",
      todo_write: "正在更新待办",
      propose_plan: "正在准备计划确认",
      deploy_app: "正在发布 App",
      open_app_preview: "正在打开 App 预览",
      mcp_tool_call: "正在使用连接",
    },
    details: "详情",
    diff: "diff",
    editNumber: (index: number, total: number) => `编辑 ${index}/${total}`,
    hide: "隐藏",
    labels: {
      bash: "命令",
      read: "读取",
      write: "写入",
      edit: "编辑",
      ask: "提问",
      task: "子 Agent",
      todo_write: "待办",
      propose_plan: "计划",
      deploy_app: "发布 App",
      open_app_preview: "App 预览",
      mcp_tool_call: "连接",
    },
    previewNeedsApproval: "需要批准",
    task: "任务",
    taskCount: (count: number) => `${count} 个任务`,
    timeout: (value: string) => `超时：${value} 毫秒`,
    working: "工作中",
  },
  userSpace: {
    add: "添加用户空间",
    agentSpace: "Agent空间",
    alreadyMounted: (name: string) => `用户空间“${name}”已经挂载。`,
    mountNameConflictDialog: {
      confirmTitle: "无法挂载同名目录",
      confirmDescription: (name: string) =>
        `已挂载名为“${name}”的用户空间。是否为这次选择的目录设置其他别名？`,
      renameAction: "设置别名",
      renameTitle: "设置用户空间别名",
      renameDescription: (name: string) => `“${name}”已被使用，请输入一个新的用户空间名称。`,
      nameLabel: "用户空间别名",
      confirmRename: "设置别名并挂载",
      enterName: "请输入新的用户空间名称。",
    },
    accessToggleTitle: (access: "readonly" | "readwrite") =>
      access === "readonly" ? "切换为读写" : "切换为只读",
    audioPreviewTitle: (name: string) => `音频预览 ${name}`,
    clipboardAnnouncements: {
      agentCut: (count: number) => `已在Agent空间剪切 ${count} 个项目。`,
      cancelled: "已取消剪切。",
      userCut: (count: number) => `已在用户空间剪切 ${count} 个项目。`,
    },
    closeCurrentPreviewTab: "关闭当前",
    closeOtherPreviewTabs: "关闭其他",
    closeAllPreviewTabs: "关闭所有",
    pinPreviewTab: "固定标签页",
    unpinPreviewTab: "取消固定标签页",
    unpinAllPreviewTabs: "取消所有固定",
    closeAllPinnedPreviewTabs: "关闭所有固定",
    closeOfficeSaveAlert: "关闭 Office 保存提示",
    closePreview: (title: string) => `关闭预览 ${title}`,
    collapseSpacePanel: "折叠用户｜Agent空间面板",
    collapsePinnedPreviewTabs: "折叠固定标签页",
    collapseSessionPanel: "折叠会话面板",
    expandSpacePanel: "展开用户｜Agent空间面板",
    expandPinnedPreviewTabs: "展开固定标签页",
    expandSessionPanel: "展开会话面板",
    textEditorLabel: (name: string) => `文本编辑器 ${name}`,
    contextMenu: {
      addToConversation: "添加到会话",
      copy: "复制",
      cut: "剪切",
      createCopy: "创建副本",
      delete: "删除",
      deleteFolder: "删除文件夹",
      details: "详情",
      newFile: "新建文件",
      newFileTypes: {
        word: "Word 文档",
        ppt: "PPT 演示文稿",
        excel: "Excel 表格",
        text: "TXT 文本",
      },
      newFolder: "新建文件夹",
      nativeQuickLook: "快速查看",
      nativeOpen: "用默认应用打开",
      nativeOpenWith: "打开方式…",
      nativeEdit: "使用本机应用编辑",
      nativeEditing: "正在本机编辑",
      nativeActionFailed: (message: string) => `文件操作失败：${message}`,
      nativeReclaim: "收回到 Piwork",
      nativeAbandon: "放弃本机编辑",
      nativePrint: "打印…",
      nativeSaveAs: "导出副本…",
      open: "打开",
      openAndPin: "打开并固定",
      openAsText: "通过文本打开",
      pasteHere: "粘贴到此处",
      pasteToRoot: (name: string) => `粘贴到${name}根目录`,
      preparingShare: "正在准备分享…",
      rename: "重命名",
      share: "分享…",
      shareFailed: (message: string) => `分享失败：${message}`,
      shareUnavailable: "无法分享此文件",
      transferToAgent: "传输到Agent空间",
      transferToUser: "传输到用户空间",
    },
    nativeEdit: {
      handoffTitle: "交给本机应用编辑？",
      handoffClean: (name: string) =>
        `“${name}”当前已在 Piwork 中打开。关闭预览后，将由默认本机应用继续编辑。`,
      handoffDirty: (name: string) =>
        `“${name}”有未保存修改。Piwork 会先保存并关闭，再交给默认本机应用。保存失败时不会打开本机应用。`,
      closeAndOpen: "关闭并用本机应用打开",
      saveCloseAndOpen: "保存并用本机应用打开",
      conflictTitle: "文件在两处都发生了变化",
      conflictDescription:
        "本机编辑期间，Piwork 中的源文件也被修改。为避免静默覆盖，请选择处理方式。",
      saveAsCopy: "保存为副本",
      overwrite: "用本机版本覆盖",
      reclaimed: "本机版本已收回到 Piwork。",
      noChanges: "本机文件没有变化，编辑交接已结束。",
      abandoned: "已放弃本机编辑，受管副本已清理。",
      savedCopy: (path: string) => `本机版本已另存为“${path}”。`,
      errors: {
        fileReadFailed: "无法读取文件内容。",
        mountUnavailable: "用户空间已离线，暂时无法收回本机编辑。",
        sourceChanged: "源文件在收回前发生了变化。",
      },
    },
    dragAndDrop: {
      agentInvalidDestination: "无法移动到该位置。",
      agentInvalidSource: "所选项目已不存在或无法移动。",
      agentMoveFailed: "无法移动所选项目；文件树已重新加载。",
      agentRollbackFailed: "移动未能完整回滚；文件树已重新加载，请检查文件当前位置。",
      agentTargetExists: "目标位置已有同名项目。",
      copySuccess: (count: number, target: string) =>
        `已将 ${count} 个项目复制到${target ? `“${target}”` : "根目录"}。`,
      items: (count: number) => `${count} 个项目`,
      moveSuccess: (count: number, target: string) =>
        `已将 ${count} 个项目移动到${target ? `“${target}”` : "根目录"}。`,
      processing: "正在处理文件…",
    },
    alerts: {
      mountSuccess: "用户空间已挂载；下次打开时可恢复访问。",
      transferAlreadyExistsTitle: "文件已存在",
      transferSuccessTitle: "文件传输成功",
    },
    createDialog: {
      folderTitle: "新建文件夹",
      fileTitle: "新建文件",
      locationRoot: "创建于用户空间根目录",
      locationPath: (path: string) => `创建于 ${path}`,
      nameLabel: "名称",
      defaultFileName: "新建文件.txt",
      defaultFileNames: {
        word: "新建word.docx",
        ppt: "新建ppt.pptx",
        excel: "新建excel.xlsx",
        text: "新建txt.txt",
      },
      processing: "处理中",
    },
    defaultFileName: "文件",
    defaultRootName: "用户空间",
    deleteDialog: {
      folderTitle: "删除文件夹？",
      fileTitle: "删除文件？",
      selectionTitle: "删除所选项目？",
      folderDescription: (path: string) => `将删除 ${path} 以及其中的内容。`,
      fileDescription: (path: string) => `将删除 ${path}。`,
      selectionDescription: (count: number) =>
        `将删除 ${count} 个所选项目；已包含在所选文件夹中的子项不会重复删除。`,
    },
    detailsDialog: {
      title: "详情",
      selectionTitle: (count: number) => `${count} 个项目详情`,
      description: (space: string) => `来自${space}`,
      selectionDescription: (space: string) => `来自${space}的所选项目`,
      labels: {
        fileCount: "文件总数量",
        name: "名称",
        modifiedAt: "修改时间",
        path: "路径",
        size: "大小",
        totalSize: "总计大小",
        type: "类型",
        typeCounts: "不同文件类型数量",
      },
      noFiles: "无文件",
      typeCount: (type: string, count: number) => `${type} ${count}`,
      typeFile: "文件",
      typeFolder: "文件夹",
      fileTypes: {
        ai: "Adobe Illustrator文稿",
        bmp: "BMP图像",
        csv: "逗号分隔值文稿",
        dmg: "磁盘映像",
        doc: "Word 97-2003文稿",
        docx: "Office Open XML字处理文稿",
        gif: "GIF图像",
        html: "HTML文稿",
        jpeg: "JPEG图像",
        jpg: "JPEG图像",
        json: "JSON文稿",
        log: "日志文件",
        markdown: "Markdown文稿",
        md: "Markdown文稿",
        mov: "QuickTime影片",
        mp3: "MP3音频",
        mp4: "MPEG-4影片",
        pdf: "PDF文稿",
        png: "PNG图像",
        ppt: "PowerPoint 97-2003演示文稿",
        pptx: "Office Open XML演示文稿",
        psd: "Adobe Photoshop文稿",
        svg: "SVG文稿",
        txt: "纯文本文稿",
        wav: "波形音频",
        webp: "WebP图像",
        xls: "Excel 97-2003工作表",
        xlsx: "Office Open XML电子表格",
        xml: "XML文稿",
        zip: "ZIP归档",
      },
      unknownSize: "未知",
    },
    searchDialog: {
      buttonTitle: "搜索文件",
      openFor: (name: string) => `搜索${name}用户空间`,
      modeLabel: "搜索模式",
      pathMode: "文件名",
      contentMode: "内容",
      inputLabel: "搜索关键词",
      pathPlaceholder: "搜索文件名...",
      contentPlaceholder: "搜索文件内容...",
      noResults: "没有匹配结果",
      openResult: (path: string) => `打开搜索结果 ${path}`,
      fileResult: "文件",
      folderResult: "文件夹",
      lineResult: (line: number) => `${line} 行`,
      matchCount: (count: number) => `${count} 次`,
    },
    directoryEmpty: "目录为空",
    directoryLoadFailed: "目录读取失败",
    directoryLoadMore: "继续加载",
    directoryLoadTimeout: "目录读取超时，请重试。",
    directoryLoading: "正在加载目录",
    directoryRuntimeRestarting: "用户空间正在恢复，稍后将自动重试。",
    restoreAccess: "恢复访问",
    restoreAccessFor: (name: string) => `恢复访问 ${name}`,
    expand: "展开",
    collapse: "收起",
    expandPreview: "展开文件预览",
    filePreview: "文件预览",
    foldPreview: "折叠文件预览",
    popOutPreviewDropHint: "松手将标签分离到新窗口",
    openPreviewInNewWindow: "在新窗口打开",
    allowPreviewPopups: "允许打开多个独立窗口",
    previewPopupsBlocked: (count: number) =>
      `Chrome 阻止了 ${count} 个独立窗口。请在地址栏的弹出式窗口提示中选择始终允许此网站，然后重试。`,
    retryOpeningPreviewWindows: "重试打开",
    returnPreviewToTabs: "移回标签组",
    wterm: {
      title: "wterm",
      open: "打开 wterm",
      requiresMountedWorkspace: "请先挂载用户空间",
    },
    htmlPreviewTitle: (name: string) => `HTML 预览 ${name}`,
    imagePreview: {
      saveFailed: "保存图片失败。",
      unsupportedFormat: "此图片格式暂不支持编辑",
      reset: "重置图片缩放",
      zoomIn: "放大图片",
      zoomOut: "缩小图片",
      editor: {
        toolbar: "图片编辑工具栏",
        select: "选择",
        crop: "裁剪",
        pen: "画笔",
        arrow: "箭头",
        rectangle: "矩形",
        ellipse: "椭圆",
        text: "文字",
        undo: "撤销",
        redo: "重做",
        color: "颜色",
        customColor: "自定义颜色",
        strokeWidth: "线条粗细",
        applyCrop: "应用裁剪",
        textPlaceholder: "输入文字",
        loading: "正在加载图片编辑器",
        loadFailed: "图片编辑器加载失败",
      },
    },
    mountMenuLabel: "用户空间目录",
    mountSwitcherDialog: {
      title: "管理用户空间目录",
      currentAria: (name: string) => `${name}，当前目录`,
      choose: (name: string) => `切换到 ${name}`,
      empty: "还没有挂载目录。",
      aliasLabel: (name: string) => `${name}的别名`,
      renameAlias: (name: string) => `重命名${name}`,
      finishRename: (name: string) => `完成重命名${name}`,
      addDirectory: "添加目录",
      save: "保存配置",
      saving: "正在保存…",
      saved: "用户空间配置已保存。",
    },
    mountRequiresSecureContext:
      "用户空间需要支持 File System Access 的安全上下文（HTTPS 或 localhost）",
    noConnection: "未连接",
    noSelection: "未选择",
    office: {
      cancelledSave: "已取消保存",
      cancelledWithDirtyFile: "已取消保存，文件仍未保存。",
      edit: "编辑",
      legacyConfirmUnavailable:
        "OnlyOffice 内置格式确认能力未加载，请刷新页面或重启 dev server 后重试。",
      localPreviewFailed: "Office 文件本地预览失败。",
      openLimitReached: "最多可同时打开 12 个 Office 文档，请先关闭一个 Office 标签后再试。",
      manageResources: "管理 Office 资源",
      prepareResources: "准备并打开",
      resourcesNotReady: "Office 资源尚未就绪，暂时无法打开编辑器。",
      resourcePreparationClose: "取消准备 Office 资源",
      resourcePreparationDescription: (size: string) =>
        `打开此文档还需要下载并校验 ${size} 的 Office 资源。完成后会自动打开文档。`,
      resourcePreparationTitle: "准备 Office 资源",
      localPreviewTimeout: "Office 文件本地预览超时，请关闭标签后重试。",
      modeSwitch: "Office 模式切换",
      noSaveAccess: "用户空间没有写入权限，无法保存 Office 文件。",
      noSaveCopyAccess: "用户空间没有写入权限，无法另存 Office 文件副本。",
      preview: "预览",
      saveCopyFailed: "Office 文件另存副本失败。",
      savedAs: (name: string) => `已另存为 ${name}`,
      savedAsCopy: (name: string) => `已另存副本为 ${name}`,
      savedAsAndDeletedOriginal: (nextName: string, originalName: string) =>
        `已保存为 ${nextName}，已删除 ${originalName}`,
      savedAsButDeleteOriginalFailed: (nextName: string, originalName: string, message: string) =>
        `已保存为 ${nextName}，但删除原始 ${originalName} 失败：${message}`,
      saveFailed: "保存失败",
      saveFileFailed: "Office 文件保存失败。",
      saving: "保存中...",
      savedToUserSpace: "已保存到用户空间",
      title: (mode: "edit" | "preview", name: string) =>
        `Office 本地${mode === "edit" ? "编辑" : "预览"} ${name}`,
    },
    pdfPreviewTitle: (name: string) => `PDF 预览 ${name}`,
    fileMovedOrMissing: (name: string) => `找不到“${name}”。`,
    previewFailed: "文件预览失败",
    previewTab: (title: string) => `切换预览 ${title}`,
    previewEntry: (name: string) => `预览 ${name}`,
    readonly: "只读",
    readwrite: "读写",
    rename: {
      aria: (name: string) => `重命名 ${name}`,
      extensionChangeTitle: "更改文件扩展名？",
      extensionChangeDescription: (currentName: string, nextName: string) =>
        `“${currentName}”将重命名为“${nextName}”。更改扩展名可能导致文件无法正常打开。`,
      extensionChangeConfirm: "仍要更改",
    },
    runtimeErrors: {
      absolutePathUnsupported: "用户空间操作不允许使用绝对路径。",
      checkoutChanged: "原始用户空间文件在 checkout 后发生变化，请重新 checkout 后再 checkin。",
      checkoutTimestampChanged:
        "原始用户空间文件时间戳在 checkout 后发生变化，请重新 checkout 后再 checkin。",
      commitAuthorizationFailed: "用户空间 checkin 写入授权失败。",
      commitLeaseMissing: "用户空间 checkin 写入授权未返回有效租约。",
      copyCleanupFailed: "复制未完成，且部分目标副本无法自动清理，请手动检查目标目录。",
      copyFolderIntoSelf: (name: string) => `不能将“${name}”复制到它自己或它的子目录中。`,
      copySelectionEmpty: "没有可复制的项目。",
      duplicateFolderUnsupported: "目录副本暂不支持。",
      entryExists: (path: string) => `用户空间条目已存在：${path}`,
      hiddenEntryUnsupported:
        "用户空间默认隐藏 . 开头的文件和文件夹，可在个人设置中开启显示或检索。",
      idbBlocked: "用户空间数据库被另一个标签页占用。",
      idbOpenFailed: "用户空间数据库打开失败。",
      mountNotFound: (_mountId: string) => "用户空间未在当前浏览器授权。",
      mountNameConflict: (name: string) => `用户空间名称“${name}”已被使用。`,
      batchTooLarge: (max: number) => `一次最多处理 ${max} 个项目。`,
      moveCleanupFailed: "移动未完成；原文件仍保留，但部分目标副本可能需要手动清理。",
      moveFolderIntoSelf: (name: string) => `不能将“${name}”移动到它自己或它的子目录中。`,
      moveSameParent: "所选项目已经位于目标文件夹中。",
      moveSelectionEmpty: "没有可移动的项目。",
      moveSourceChanged: (path: string) => `“${path}”在复制过程中发生变化，已取消操作。`,
      readwriteRequired: (name: string) =>
        `用户空间 "${name}" 当前为只读，请切换为读写后再修改文件。`,
      renameFolderUnsupported: "目录重命名暂不支持，请先新建目录后移动具体文件。",
      sha256Unsupported: "当前浏览器不支持用户空间传输所需的 SHA-256 校验。",
      unsupportedOperation: (operation: string) => `不支持的用户空间操作：${operation}`,
      uniqueCopyNameFailed: "无法生成可用的副本文件名。",
    },
    resetCopySuffix: "_副本",
    copySuffix: "副本",
    saveFailed: "保存失败",
    selectSpace: "空间切换",
    setAccess: (name: string, access: "readonly" | "readwrite") =>
      `设置${name}为${access === "readonly" ? "只读" : "读写"}`,
    switchMount: (name: string) => `切换用户空间目录，当前 ${name}`,
    switchConfirm: {
      title: "切换用户空间目录？",
      description: (name: string, count: number) =>
        count > 0
          ? `切换到 ${name} 会关闭当前目录已打开的 ${count} 个文件预览；未保存修改会丢失。`
          : `确认切换到 ${name}？`,
      continueSwitch: "继续切换",
    },
    toggleDirectory: (expanded: boolean, name: string) => `${expanded ? "收起" : "展开"} ${name}`,
    toggleMount: (expanded: boolean, name: string) =>
      `${expanded ? "收起" : "展开"}${name}用户空间`,
    syncIndex: "同步空间索引",
    syncIndexFor: (name: string) => `同步${name}空间索引`,
    textSaveAction: {
      edit: "编辑",
      partial: "文件仅加载了部分内容",
      readonly: "用户空间为只读",
      save: "保存",
    },
    textSaveErrors: {
      fileTooLarge: "文件过大，仅加载了部分内容，不能直接保存。",
      tabMissing: "预览标签不存在。",
      textReadFailed: "文件文本读取失败。",
      unsupportedType: "此文件类型不支持文本保存。",
    },
    truncatedNotice: (name: string, size: string) => `仅显示 ${name} 的前 ${size}。`,
    unmount: "取消挂载",
    unmountFor: (name: string) => `取消挂载${name}`,
    unmountConfirm: {
      title: "移除用户空间目录？",
      description: (name: string) => `将“${name}”从当前会话移除。本地文件不会被删除。`,
      confirm: "移除目录",
    },
    unsupportedPreview: "无法预览此文件类型，可以用本地应用打开。",
    unsavedClose: {
      titleMany: (count: number) => `关闭 ${count} 个未保存文件？`,
      titleOne: "关闭未保存文件？",
      descriptionMany: (count: number) =>
        `有 ${count} 个文件包含未保存的修改，继续关闭会丢失这些更改。`,
      descriptionOne: (name: string) => `${name} 有未保存的修改，继续关闭会丢失这些更改。`,
      continueClose: "继续关闭",
    },
    userSpace: "用户空间",
    validation: {
      emptyName: "名称不能为空。",
      hiddenName: ". 开头的名称会默认隐藏，可在个人设置中开启显示。",
      invalidCharacters: "名称不能包含无效字符。",
      invalidDots: "名称不能使用 . 或 ..。",
      pathSeparator: "名称不能包含路径分隔符。",
      tooLong: "名称过长。",
    },
    videoPreviewTitle: (name: string) => `视频预览 ${name}`,
    workspaceSidebar: "工作区文件边栏",
    workspaceTree: "工作区文件树",
    workspaceTreeLabel: "用户空间文件树",
    unsupportedActions: {
      duplicateFolderPending: "当前版本先支持文件副本，目录副本会在递归策略确定后再补。",
      pasteFolderInsideSelf: (name: string) => `不能将“${name}”粘贴到它自己或它的子目录中。`,
      pasteSameMountOnly: "当前版本仅支持在同一个用户空间内复制粘贴。",
      renameFolderPending: "当前版本先支持文件重命名，目录重命名稍后再做。",
    },
  },
} as const;
